<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Sources of AUC variability | The RJafroc Roc Book</title>
  <meta name="description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Sources of AUC variability | The RJafroc Roc Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="github-repo" content="dpc10ster/RJafrocRocBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Sources of AUC variability | The RJafroc Roc Book" />
  
  <meta name="twitter:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2023-03-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="hypothesis-testing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#rationale-and-organization"><i class="fa fa-check"></i><b>0.1</b> Rationale and Organization</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#tba-acknowledgements"><i class="fa fa-check"></i><b>0.2</b> TBA Acknowledgements</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#temporary-comments"><i class="fa fa-check"></i><b>0.3</b> Temporary comments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="sources-of-variability.html"><a href="sources-of-variability.html"><i class="fa fa-check"></i><b>1</b> Sources of AUC variability</a><ul>
<li class="chapter" data-level="1.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-how-much-finished"><i class="fa fa-check"></i><b>1.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="1.2" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityIntro"><i class="fa fa-check"></i><b>1.2</b> Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability3sources"><i class="fa fa-check"></i><b>1.3</b> Three sources of variability</a></li>
<li class="chapter" data-level="1.4" data-path="sources-of-variability.html"><a href="sources-of-variability.html#dependence-of-auc-on-the-case-sample"><i class="fa fa-check"></i><b>1.4</b> Dependence of AUC on the case sample</a><ul>
<li class="chapter" data-level="1.4.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#case-sampling-variability-of-auc"><i class="fa fa-check"></i><b>1.4.1</b> Case sampling variability of AUC</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityDeLong"><i class="fa fa-check"></i><b>1.5</b> DeLong method</a></li>
<li class="chapter" data-level="1.6" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityBootstrap"><i class="fa fa-check"></i><b>1.6</b> Bootstrap method</a><ul>
<li class="chapter" data-level="1.6.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#demonstration-of-the-bootstrap-method"><i class="fa fa-check"></i><b>1.6.1</b> Demonstration of the bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityJackknife"><i class="fa fa-check"></i><b>1.7</b> Jackknife method</a></li>
<li class="chapter" data-level="1.8" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityCalSimulator"><i class="fa fa-check"></i><b>1.8</b> Calibrated simulator</a><ul>
<li class="chapter" data-level="1.8.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#the-need-for-a-calibrated-simulator"><i class="fa fa-check"></i><b>1.8.1</b> The need for a calibrated simulator</a></li>
<li class="chapter" data-level="1.8.2" data-path="sources-of-variability.html"><a href="sources-of-variability.html#implementation-of-a-simple-calibrated-simulator"><i class="fa fa-check"></i><b>1.8.2</b> Implementation of a simple calibrated simulator</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-Discussion"><i class="fa fa-check"></i><b>1.9</b> Discussion</a></li>
<li class="chapter" data-level="1.10" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-references"><i class="fa fa-check"></i><b>1.10</b> Chapter References</a></li>
</ul></li>
<li class="part"><span><b>Significance Testing</b></span></li>
<li class="chapter" data-level="2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-how-much-finished"><i class="fa fa-check"></i><b>2.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-introduction"><i class="fa fa-check"></i><b>2.2</b> Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#single-modality-single-reader-roc-study"><i class="fa fa-check"></i><b>2.3</b> Single-modality single-reader ROC study</a></li>
<li class="chapter" data-level="2.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#type-i-errors"><i class="fa fa-check"></i><b>2.4</b> Type-I errors</a></li>
<li class="chapter" data-level="2.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-vs.-two-sided-tests"><i class="fa fa-check"></i><b>2.5</b> One vs. two sided tests</a></li>
<li class="chapter" data-level="2.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-power"><i class="fa fa-check"></i><b>2.6</b> Statistical power</a><ul>
<li class="chapter" data-level="2.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#factors-affecting-statistical-power"><i class="fa fa-check"></i><b>2.6.1</b> Factors affecting statistical power</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testingComments"><i class="fa fa-check"></i><b>2.7</b> Comments</a></li>
<li class="chapter" data-level="2.8" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#why-alpha-is-chosen-as-5"><i class="fa fa-check"></i><b>2.8</b> Why alpha is chosen as 5%</a></li>
<li class="chapter" data-level="2.9" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testingDiscussion"><i class="fa fa-check"></i><b>2.9</b> Discussion</a></li>
<li class="chapter" data-level="2.10" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-references"><i class="fa fa-check"></i><b>2.10</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html"><i class="fa fa-check"></i><b>3</b> DBM method background</a><ul>
<li class="chapter" data-level="3.1" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-how-much-finished"><i class="fa fa-check"></i><b>3.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="3.2" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-introduction"><i class="fa fa-check"></i><b>3.2</b> Introduction</a><ul>
<li class="chapter" data-level="3.2.1" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#historical-background"><i class="fa fa-check"></i><b>3.2.1</b> Historical background</a></li>
<li class="chapter" data-level="3.2.2" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#the-wagner-analogy"><i class="fa fa-check"></i><b>3.2.2</b> The Wagner analogy</a></li>
<li class="chapter" data-level="3.2.3" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#the-shortage-of-numbers-to-analyze-and-a-pivotal-breakthrough"><i class="fa fa-check"></i><b>3.2.3</b> The shortage of numbers to analyze and a pivotal breakthrough</a></li>
<li class="chapter" data-level="3.2.4" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#organization-of-chapter"><i class="fa fa-check"></i><b>3.2.4</b> Organization of chapter</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-random-fixed-factors"><i class="fa fa-check"></i><b>3.3</b> Random and fixed factors</a></li>
<li class="chapter" data-level="3.4" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-reader-case-populations"><i class="fa fa-check"></i><b>3.4</b> Reader and case populations</a></li>
<li class="chapter" data-level="3.5" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-threeAnalyses"><i class="fa fa-check"></i><b>3.5</b> Three types of analyses</a></li>
<li class="chapter" data-level="3.6" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-approach"><i class="fa fa-check"></i><b>3.6</b> General approach</a></li>
<li class="chapter" data-level="3.7" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-summary"><i class="fa fa-check"></i><b>3.7</b> Summary TBA</a></li>
<li class="chapter" data-level="3.8" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-references"><i class="fa fa-check"></i><b>3.8</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html"><i class="fa fa-check"></i><b>4</b> Significance Testing using the DBM Method</a><ul>
<li class="chapter" data-level="4.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-how-much-finished"><i class="fa fa-check"></i><b>4.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="4.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-dbm-sampling-model"><i class="fa fa-check"></i><b>4.2</b> The DBM sampling model</a><ul>
<li class="chapter" data-level="4.2.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#explanation-of-terms-in-the-model"><i class="fa fa-check"></i><b>4.2.1</b> Explanation of terms in the model</a></li>
<li class="chapter" data-level="4.2.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#meanings-of-variance-components-in-the-dbm-model-tba-this-section-can-be-improved"><i class="fa fa-check"></i><b>4.2.2</b> Meanings of variance components in the DBM model (<strong>TBA this section can be improved</strong>)</a></li>
<li class="chapter" data-level="4.2.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#definitions-of-mean-squares"><i class="fa fa-check"></i><b>4.2.3</b> Definitions of mean-squares</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#expected-values-of-mean-squares"><i class="fa fa-check"></i><b>4.3</b> Expected values of mean squares</a></li>
<li class="chapter" data-level="4.4" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-RRRC-analysis"><i class="fa fa-check"></i><b>4.4</b> Random-reader random-case (RRRC) analysis</a><ul>
<li class="chapter" data-level="4.4.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#calculation-of-mean-squares-an-example"><i class="fa fa-check"></i><b>4.4.1</b> Calculation of mean squares: an example</a></li>
<li class="chapter" data-level="4.4.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-sig-testing"><i class="fa fa-check"></i><b>4.4.2</b> Significance testing</a></li>
<li class="chapter" data-level="4.4.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-satterthwaite-approximation"><i class="fa fa-check"></i><b>4.4.3</b> The Satterthwaite approximation</a></li>
<li class="chapter" data-level="4.4.4" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#decision-rules-p-value-and-confidence-intervals"><i class="fa fa-check"></i><b>4.4.4</b> Decision rules, p-value and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#sample-size-estimation-for-random-reader-random-case-generalization"><i class="fa fa-check"></i><b>4.5</b> Sample size estimation for random-reader random-case generalization</a><ul>
<li class="chapter" data-level="4.5.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-non-centrality-parameter"><i class="fa fa-check"></i><b>4.5.1</b> The non-centrality parameter</a></li>
<li class="chapter" data-level="4.5.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-denominator-degrees-of-freedom"><i class="fa fa-check"></i><b>4.5.2</b> The denominator degrees of freedom</a></li>
<li class="chapter" data-level="4.5.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#example-of-sample-size-estimation-rrrc-generalization"><i class="fa fa-check"></i><b>4.5.3</b> Example of sample size estimation, RRRC generalization</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#significance-testing-and-sample-size-estimation-for-fixed-reader-random-case-generalization"><i class="fa fa-check"></i><b>4.6</b> Significance testing and sample size estimation for fixed-reader random-case generalization</a></li>
<li class="chapter" data-level="4.7" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#significance-testing-and-sample-size-estimation-for-random-reader-fixed-case-generalization"><i class="fa fa-check"></i><b>4.7</b> Significance testing and sample size estimation for random-reader fixed-case generalization</a></li>
<li class="chapter" data-level="4.8" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-summary"><i class="fa fa-check"></i><b>4.8</b> Summary TBA</a></li>
<li class="chapter" data-level="4.9" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#things-for-me-to-think-about"><i class="fa fa-check"></i><b>4.9</b> Things for me to think about</a><ul>
<li class="chapter" data-level="4.9.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#expected-values-of-mean-squares-1"><i class="fa fa-check"></i><b>4.9.1</b> Expected values of mean squares</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-references"><i class="fa fa-check"></i><b>4.10</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html"><i class="fa fa-check"></i><b>5</b> DBM method special cases</a><ul>
<li class="chapter" data-level="5.1" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-fits-how-much-finished"><i class="fa fa-check"></i><b>5.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="5.2" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#FRRCDBMAnalysis"><i class="fa fa-check"></i><b>5.2</b> Fixed-reader random-case (FRRC) analysis</a><ul>
<li class="chapter" data-level="5.2.1" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#FRRCSingleReaderDBMAnalysis"><i class="fa fa-check"></i><b>5.2.1</b> Single-reader multiple-treatment analysis</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-RRFCAnalysis"><i class="fa fa-check"></i><b>5.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="5.4" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-references"><i class="fa fa-check"></i><b>5.4</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="or-method-intro.html"><a href="or-method-intro.html"><i class="fa fa-check"></i><b>6</b> Introduction to the Obuchowski-Rockette method</a><ul>
<li class="chapter" data-level="6.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-how-much-finished"><i class="fa fa-check"></i><b>6.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="6.2" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-helper-functions"><i class="fa fa-check"></i><b>6.2</b> Locations of helper functions</a></li>
<li class="chapter" data-level="6.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-intro"><i class="fa fa-check"></i><b>6.3</b> Introduction</a></li>
<li class="chapter" data-level="6.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader"><i class="fa fa-check"></i><b>6.4</b> Single-reader multiple-treatment</a><ul>
<li class="chapter" data-level="6.4.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-overview"><i class="fa fa-check"></i><b>6.4.1</b> Overview</a></li>
<li class="chapter" data-level="6.4.2" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-treatment"><i class="fa fa-check"></i><b>6.4.2</b> Significance testing</a></li>
<li class="chapter" data-level="6.4.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-pvalue-ci"><i class="fa fa-check"></i><b>6.4.3</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="6.4.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-nh-validation"><i class="fa fa-check"></i><b>6.4.4</b> Null hypothesis validation</a></li>
<li class="chapter" data-level="6.4.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-application-roc"><i class="fa fa-check"></i><b>6.4.5</b> Application 1</a></li>
<li class="chapter" data-level="6.4.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-application-froc"><i class="fa fa-check"></i><b>6.4.6</b> Application 2</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-treatment"><i class="fa fa-check"></i><b>6.5</b> Single-treatment multiple-reader</a><ul>
<li class="chapter" data-level="6.5.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-treatment-overview"><i class="fa fa-check"></i><b>6.5.1</b> Overview</a></li>
<li class="chapter" data-level="6.5.2" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-reader"><i class="fa fa-check"></i><b>6.5.2</b> Significance testing</a></li>
<li class="chapter" data-level="6.5.3" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-reader-example-three"><i class="fa fa-check"></i><b>6.5.3</b> Special case</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-multiple-reader-multiple-treatment"><i class="fa fa-check"></i><b>6.6</b> Multiple-reader multiple-treatment</a><ul>
<li class="chapter" data-level="6.6.1" data-path="or-method-intro.html"><a href="or-method-intro.html#StrCovMatrix"><i class="fa fa-check"></i><b>6.6.1</b> Structure of the covariance matrix</a></li>
<li class="chapter" data-level="6.6.2" data-path="or-method-intro.html"><a href="or-method-intro.html#PhysicalMeaningsOfCovMatrix"><i class="fa fa-check"></i><b>6.6.2</b> Physical meanings of the covariance terms</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-summary"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
<li class="chapter" data-level="6.8" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-discussion"><i class="fa fa-check"></i><b>6.8</b> Discussion</a></li>
<li class="chapter" data-level="6.9" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats"><i class="fa fa-check"></i><b>6.9</b> Appendix: Covariance and correlation</a><ul>
<li class="chapter" data-level="6.9.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-f-stat-chisq-stat"><i class="fa fa-check"></i><b>6.9.1</b> Relation: chisquare and F with infinite ddf</a></li>
<li class="chapter" data-level="6.9.2" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-def-cov-matrix"><i class="fa fa-check"></i><b>6.9.2</b> Definitions of covariance and correlation</a></li>
<li class="chapter" data-level="6.9.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-equal-variance"><i class="fa fa-check"></i><b>6.9.3</b> Special case when variables have equal variances</a></li>
<li class="chapter" data-level="6.9.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-est-cov-matrix"><i class="fa fa-check"></i><b>6.9.4</b> Estimating the variance-covariance matrix</a></li>
<li class="chapter" data-level="6.9.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-jack-var-inflation-factor"><i class="fa fa-check"></i><b>6.9.5</b> The variance inflation factor</a></li>
<li class="chapter" data-level="6.9.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-meaning-cov-matrix"><i class="fa fa-check"></i><b>6.9.6</b> Meaning of the covariance matrix</a></li>
<li class="chapter" data-level="6.9.7" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-code-cov-matrix"><i class="fa fa-check"></i><b>6.9.7</b> Code illustrating the covariance matrix</a></li>
<li class="chapter" data-level="6.9.8" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-compare-dbm-or"><i class="fa fa-check"></i><b>6.9.8</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-references"><i class="fa fa-check"></i><b>6.10</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="or-analysis-st.html"><a href="or-analysis-st.html"><i class="fa fa-check"></i><b>7</b> Obuchowski Rockette (OR) Analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-how-much-finished"><i class="fa fa-check"></i><b>7.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="7.2" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-introduction"><i class="fa fa-check"></i><b>7.2</b> Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-rrrc"><i class="fa fa-check"></i><b>7.3</b> Random-reader random-case</a><ul>
<li class="chapter" data-level="7.3.1" data-path="or-analysis-st.html"><a href="or-analysis-st.html#TwoAnecdotes"><i class="fa fa-check"></i><b>7.3.1</b> Two anecdotes</a></li>
<li class="chapter" data-level="7.3.2" data-path="or-analysis-st.html"><a href="or-analysis-st.html#Hills-ddf"><i class="fa fa-check"></i><b>7.3.2</b> Hillis ddf</a></li>
<li class="chapter" data-level="7.3.3" data-path="or-analysis-st.html"><a href="or-analysis-st.html#decision-rule-p-value-and-confidence-interval"><i class="fa fa-check"></i><b>7.3.3</b> Decision rule, p-value and confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-frrc"><i class="fa fa-check"></i><b>7.4</b> Fixed-reader random-case</a></li>
<li class="chapter" data-level="7.5" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-rrfc"><i class="fa fa-check"></i><b>7.5</b> Random-reader fixed-case</a></li>
<li class="chapter" data-level="7.6" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-single-treatment"><i class="fa fa-check"></i><b>7.6</b> Single treatment analysis</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="or-applications.html"><a href="or-applications.html"><i class="fa fa-check"></i><b>8</b> Obuchowski Rockette Applications</a><ul>
<li class="chapter" data-level="8.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-how-much-finished"><i class="fa fa-check"></i><b>8.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="8.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-introduction"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset02-hand"><i class="fa fa-check"></i><b>8.3</b> Hand calculation</a><ul>
<li class="chapter" data-level="8.3.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset02-hand"><i class="fa fa-check"></i><b>8.3.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="8.3.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset02-hand"><i class="fa fa-check"></i><b>8.3.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="8.3.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset02-hand"><i class="fa fa-check"></i><b>8.3.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset02-RJafroc"><i class="fa fa-check"></i><b>8.4</b> RJafroc: dataset02</a><ul>
<li class="chapter" data-level="8.4.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>8.4.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="8.4.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>8.4.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="8.4.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset02-RJafroc"><i class="fa fa-check"></i><b>8.4.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-RJafroc"><i class="fa fa-check"></i><b>8.5</b> RJafroc: dataset04</a><ul>
<li class="chapter" data-level="8.5.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04"><i class="fa fa-check"></i><b>8.5.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="8.5.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04"><i class="fa fa-check"></i><b>8.5.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="8.5.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04"><i class="fa fa-check"></i><b>8.5.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-FROC-RJafroc"><i class="fa fa-check"></i><b>8.6</b> RJafroc: dataset04, FROC</a><ul>
<li class="chapter" data-level="8.6.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04-FROC"><i class="fa fa-check"></i><b>8.6.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="8.6.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04-FROC"><i class="fa fa-check"></i><b>8.6.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="8.6.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04-FROC"><i class="fa fa-check"></i><b>8.6.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-FROC-DBM-RJafroc"><i class="fa fa-check"></i><b>8.7</b> RJafroc: dataset04, FROC/DBM</a><ul>
<li class="chapter" data-level="8.7.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>8.7.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="8.7.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>8.7.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="8.7.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>8.7.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="or-applications.html"><a href="or-applications.html#or-applications-Summary"><i class="fa fa-check"></i><b>8.8</b> Summary</a></li>
<li class="chapter" data-level="8.9" data-path="or-applications.html"><a href="or-applications.html#or-applications-Discussion"><i class="fa fa-check"></i><b>8.9</b> Discussion</a></li>
<li class="chapter" data-level="8.10" data-path="or-applications.html"><a href="or-applications.html#ToMullOver1-tentative"><i class="fa fa-check"></i><b>8.10</b> Tentative</a></li>
<li class="chapter" data-level="8.11" data-path="or-applications.html"><a href="or-applications.html#or-applications-references"><i class="fa fa-check"></i><b>8.11</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html"><i class="fa fa-check"></i><b>9</b> Sample size estimation: DBM method</a><ul>
<li class="chapter" data-level="9.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-how-much-finished"><i class="fa fa-check"></i><b>9.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="9.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-introduction"><i class="fa fa-check"></i><b>9.2</b> Introduction</a></li>
<li class="chapter" data-level="9.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#StatPower1"><i class="fa fa-check"></i><b>9.3</b> Statistical Power</a><ul>
<li class="chapter" data-level="9.3.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#observed-vs.-anticipated-effect-size"><i class="fa fa-check"></i><b>9.3.1</b> Observed vs. anticipated effect-size</a></li>
<li class="chapter" data-level="9.3.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-dependence-of-stats-power"><i class="fa fa-check"></i><b>9.3.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="9.3.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>9.3.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="9.3.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-sig-testing"><i class="fa fa-check"></i><b>9.3.4</b> Significance testing</a></li>
<li class="chapter" data-level="9.3.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-pvalue-ci"><i class="fa fa-check"></i><b>9.3.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="9.3.6" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-CompareDBM2OR"><i class="fa fa-check"></i><b>9.3.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>9.4</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a><ul>
<li class="chapter" data-level="9.4.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>9.4.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="9.4.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRCAnalysis"><i class="fa fa-check"></i><b>9.4.2</b> Fixed-reader random-case (FRRC) analysis TBA</a></li>
<li class="chapter" data-level="9.4.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFCAnalysis"><i class="fa fa-check"></i><b>9.4.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="9.4.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-STMRAnalysis"><i class="fa fa-check"></i><b>9.4.4</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#discussionsummary2"><i class="fa fa-check"></i><b>9.5</b> Discussion/Summary/2</a></li>
<li class="chapter" data-level="9.6" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-references"><i class="fa fa-check"></i><b>9.6</b> Chapter References</a></li>
</ul></li>
<li class="part"><span><b>RJafroc Vignettes</b></span></li>
<li class="chapter" data-level="10" data-path="background-f-distribution.html"><a href="background-f-distribution.html"><i class="fa fa-check"></i><b>10</b> F-distribution</a><ul>
<li class="chapter" data-level="10.1" data-path="background-f-distribution.html"><a href="background-f-distribution.html#background-f-distribution-how-much-finished"><i class="fa fa-check"></i><b>10.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="10.2" data-path="background-f-distribution.html"><a href="background-f-distribution.html#introduction"><i class="fa fa-check"></i><b>10.2</b> Introduction</a></li>
<li class="chapter" data-level="10.3" data-path="background-f-distribution.html"><a href="background-f-distribution.html#effect-of-ncp-for-ndf-2-and-ddf-10"><i class="fa fa-check"></i><b>10.3</b> Effect of <code>ncp</code> for <code>ndf</code> = 2 and <code>ddf</code> = 10</a></li>
<li class="chapter" data-level="10.4" data-path="background-f-distribution.html"><a href="background-f-distribution.html#comments"><i class="fa fa-check"></i><b>10.4</b> Comments</a><ul>
<li class="chapter" data-level="10.4.1" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-a"><i class="fa fa-check"></i><b>10.4.1</b> Fig. A</a></li>
<li class="chapter" data-level="10.4.2" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-b"><i class="fa fa-check"></i><b>10.4.2</b> Fig. B</a></li>
<li class="chapter" data-level="10.4.3" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-c"><i class="fa fa-check"></i><b>10.4.3</b> Fig. C</a></li>
<li class="chapter" data-level="10.4.4" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-d"><i class="fa fa-check"></i><b>10.4.4</b> Fig. D</a></li>
<li class="chapter" data-level="10.4.5" data-path="background-f-distribution.html"><a href="background-f-distribution.html#summary"><i class="fa fa-check"></i><b>10.4.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="background-f-distribution.html"><a href="background-f-distribution.html#effect-of-ncp-for-ndf-2-and-ddf-100"><i class="fa fa-check"></i><b>10.5</b> Effect of <code>ncp</code> for <code>ndf</code> = 2 and <code>ddf</code> = 100</a></li>
<li class="chapter" data-level="10.6" data-path="background-f-distribution.html"><a href="background-f-distribution.html#comments-1"><i class="fa fa-check"></i><b>10.6</b> Comments</a><ul>
<li class="chapter" data-level="10.6.1" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-e"><i class="fa fa-check"></i><b>10.6.1</b> Fig. E</a></li>
<li class="chapter" data-level="10.6.2" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-f"><i class="fa fa-check"></i><b>10.6.2</b> Fig. F</a></li>
<li class="chapter" data-level="10.6.3" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-g"><i class="fa fa-check"></i><b>10.6.3</b> Fig. G</a></li>
<li class="chapter" data-level="10.6.4" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-h"><i class="fa fa-check"></i><b>10.6.4</b> Fig. H</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="background-f-distribution.html"><a href="background-f-distribution.html#effect-of-ncp-for-ndf-1-ddf-100"><i class="fa fa-check"></i><b>10.7</b> Effect of <code>ncp</code> for <code>ndf</code> = 1, <code>ddf</code> = 100</a></li>
<li class="chapter" data-level="10.8" data-path="background-f-distribution.html"><a href="background-f-distribution.html#comments-2"><i class="fa fa-check"></i><b>10.8</b> Comments</a><ul>
<li class="chapter" data-level="10.8.1" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-i"><i class="fa fa-check"></i><b>10.8.1</b> Fig. I</a></li>
<li class="chapter" data-level="10.8.2" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-j"><i class="fa fa-check"></i><b>10.8.2</b> Fig. J</a></li>
<li class="chapter" data-level="10.8.3" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-k"><i class="fa fa-check"></i><b>10.8.3</b> Fig. K</a></li>
<li class="chapter" data-level="10.8.4" data-path="background-f-distribution.html"><a href="background-f-distribution.html#fig.-l"><i class="fa fa-check"></i><b>10.8.4</b> Fig. L</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="background-f-distribution.html"><a href="background-f-distribution.html#summary-1"><i class="fa fa-check"></i><b>10.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html"><i class="fa fa-check"></i><b>11</b> Sample size estimation: OR method</a><ul>
<li class="chapter" data-level="11.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-how-much-finished"><i class="fa fa-check"></i><b>11.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="11.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-introduction"><i class="fa fa-check"></i><b>11.2</b> Introduction</a></li>
<li class="chapter" data-level="11.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#StatPower2"><i class="fa fa-check"></i><b>11.3</b> Statistical Power</a><ul>
<li class="chapter" data-level="11.3.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#sample-size-estimation-for-random-reader-random-cases"><i class="fa fa-check"></i><b>11.3.1</b> Sample size estimation for random-reader random-cases</a></li>
<li class="chapter" data-level="11.3.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-dependence-of-stats-power"><i class="fa fa-check"></i><b>11.3.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="11.3.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>11.3.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="11.3.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-sig-testing"><i class="fa fa-check"></i><b>11.3.4</b> Significance testing</a></li>
<li class="chapter" data-level="11.3.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-pvalue-ci"><i class="fa fa-check"></i><b>11.3.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="11.3.6" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-CompareDBM2OR"><i class="fa fa-check"></i><b>11.3.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>11.4</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a><ul>
<li class="chapter" data-level="11.4.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>11.4.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="11.4.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#example-1"><i class="fa fa-check"></i><b>11.4.2</b> Example 1</a></li>
<li class="chapter" data-level="11.4.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-FRRCAnalysis"><i class="fa fa-check"></i><b>11.4.3</b> Fixed-reader random-case (FRRC) analysis</a></li>
<li class="chapter" data-level="11.4.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRFCAnalysis"><i class="fa fa-check"></i><b>11.4.4</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="11.4.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-STMRAnalysis"><i class="fa fa-check"></i><b>11.4.5</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#discussionsummary3"><i class="fa fa-check"></i><b>11.5</b> Discussion/Summary/3</a></li>
<li class="chapter" data-level="11.6" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-references"><i class="fa fa-check"></i><b>11.6</b> Chapter References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Roc Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sources-of-variability" class="section level1 hasAnchor">
<h1><span class="header-section-number">Chapter 1</span> Sources of AUC variability<a href="sources-of-variability.html#sources-of-variability" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="sources-of-variability-how-much-finished" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.1</span> TBA How much finished<a href="sources-of-variability.html#sources-of-variability-how-much-finished" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>60%</p>
</div>
<div id="sources-of-variabilityIntro" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.2</span> Introduction<a href="sources-of-variability.html#sources-of-variabilityIntro" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In previous chapters the area AUC under the ROC plot was introduced as the preferred way of summarizing performance in the ROC task, as compared to a pair of sensitivity and specificity values. It can be estimated either non-parametrically, as in <code>TempComment Chapter \@ref(empirical-auc)</code>, or parametrically, as in Chapter <code>TempComment \@ref(binormal-model)</code>, and even better ways of estimating it are described in TBA Chapter 18 and Chapter 20.</p>
<p>Irrespective of how it is estimated AUC is a realization of a random variable, and as such, it is subject to sampling variability. Any measurement based on a finite number of samples from a parent population is subject to sampling variability. This is because no finite sample is unique: someone else conducting a similar study would, in general, obtain a different sample. [Case-sampling variability is estimated by the binormal model in the previous chapter. It is related to the sharpness of the peak of the likelihood function, TBA §6.4.4. The sharper that the peak, the smaller the case sampling variability. This chapter focuses on general sources of variability affecting AUC, regardless of how it is estimated, and other (i.e., not binormal model based) ways of estimating it.]</p>
<p>Here is an outline of this chapter. The starting point is the identification of different sources of variability affecting AUC estimates. Considered next is dependence of AUC on the case-set index <span class="math inline">\(\{c\}\)</span>, <span class="math inline">\(c = 1,2,...,C\)</span>. Considered next is estimating case-sampling variability of the empirical estimate of AUC by an analytic method. This is followed by descriptions of two resampling-based methods, namely the bootstrap and the jackknife, both of which have wide applicability (i.e., they are not restricted to ROC analysis). The methods are demonstrated using <code>R</code> code and the implementation of a calibrated simulator is shown and used to demonstrate their validity, i.e., showing that the different methods of estimating variability agree. The dependence of AUC on reader expertise and modality is considered. An important source of variability, namely the radiologist’s choice of internal sensory thresholds, is described. A cautionary comment is made regarding indiscriminate usage of empirical AUC as a measure of performance.</p>
<p>TBA Online Appendix 7.A describes coding of the bootstrap method; Online Appendix 7.B is the corresponding implementation of the jackknife method. Online Appendix 7.C describes implementation of the calibrated simulator for single-modality single-reader ROC datasets. Online Appendix 7.D describes the code that allows comparison of the different methods of estimating case-sampling variability.</p>
</div>
<div id="sources-of-variability3sources" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.3</span> Three sources of variability<a href="sources-of-variability.html#sources-of-variability3sources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Statistics deals with variability. Understanding sources of variability affecting AUC is critical to an appreciation of ROC analysis. Three sources of variability are identified in <span class="citation">(Swets and Pickett <a href="#ref-RN412" role="doc-biblioref">1982</a>)</span>: case sampling, between-reader and within-reader variability.</p>
<ol style="list-style-type: decimal">
<li>Consider a single reader interpreting different case samples. Case-sampling variability arises from the finite number of cases comprising the dataset, compared to the potentially very large population of cases. [If one could sample every case there exists and have them interpreted by the same reader, there would be no case-sampling variability and the poor reader’s AUC values (from repeated interpretations of the entire population) would reflect only within reader variability, see #3 below.] Each case-set <span class="math inline">\(\{c\}\)</span>, consisting of <span class="math inline">\(K_1\)</span> non-diseased and <span class="math inline">\(K_2\)</span> diseased cases interpreted by the reader, yields an AUC value. The notation <span class="math inline">\(\{c\}\)</span> means different <em>case sets</em>. Thus <span class="math inline">\(\{c\}\)</span> = <span class="math inline">\(\{1\}\)</span>, <span class="math inline">\(\{2\}\)</span>, etc., denote different case sets, each consisting of <span class="math inline">\(K_1\)</span> non-diseased and <span class="math inline">\(K_2\)</span> diseased cases.</li>
</ol>
<p>There is much “data compression” in going from individual case ratings to AUC. For a single reader and given case-set <span class="math inline">\(\{c\}\)</span>, the ratings can be converted to an <span class="math inline">\(A_{z\{c\}}\)</span> estimate, TBA Eqn. (6.49). The notation shows explicitly the dependence of the measure on the case-set <span class="math inline">\(\{c\}\)</span>. One can conceptualize the distribution of <span class="math inline">\(A_{z\{c\}}\)</span>’s over different case-sets, each of the same size <span class="math inline">\(K_1+K_2\)</span>, as a normal distribution, i.e.,</p>
<p><span class="math display" id="eq:sources-of-variability-cs-wr">\[\begin{equation} 
A_{z\{c\}}\sim N(A_{z\{\bullet\}},\sigma_{\text{cs+wr}}^2)
\tag{1.1}
\end{equation}\]</span></p>
<p>The dot notation <span class="math inline">\(\{\bullet\}\)</span> denotes an average over all case sets. Thus, <span class="math inline">\(A_{z\{\bullet\}}\)</span> is an estimate of the case-sampling mean of <span class="math inline">\(A_z\)</span> for a single fixed reader and <span class="math inline">\(\sigma_{\text{cs+wr}}^2\)</span> is the <em>case sampling plus within-reader</em> variance. The reason for adding the within-reader variance is explained in #3 below. The concept is that a specified reader interpreting different case-sets effectively samples different parts of the population of cases, resulting in variability in measured <span class="math inline">\(A_z\)</span>. Sometimes easier cases are sampled, and sometimes more difficult ones. This source of variability is expected to decrease with increasing case-set size, i.e., increasing <span class="math inline">\(K_1+K_2\)</span>, which is the reason for seeking large numbers of cases in clinical trials. Case-sampling and within-reader variability also decreases as the cases become more homogenous. An example of a more homogenous case sample would be cases originating from a small geographical region with, for example, limited ethnic variability. This is the reason for seeking multi-institutional clinical trials, because they tend to sample more of the population than patients seen at a single institution.</p>
<ol start="2" style="list-style-type: decimal">
<li>Consider different readers interpreting a fixed case sample. Between-reader variability arises from the finite number of readers compared to the population of readers; the population of readers could be all board certified radiologists interpreting screening mammograms in the US. This time one envisages different readers interpreting a fixed case set <span class="math inline">\(\{1\}\)</span>. The different reader’s <span class="math inline">\(A_{z;j}\)</span> values (<span class="math inline">\(j\)</span> is the reader index, <span class="math inline">\(j = 1, 2, ..., J\)</span>, where <span class="math inline">\(J\)</span> is the total number of readers in the dataset) are distributed:</li>
</ol>
<p><span class="math display" id="eq:sources-of-variability-br-wr">\[\begin{equation} 
A_{z;j}\sim N(A_{z;\bullet},\sigma_{\text{br+wr}}^2)
\tag{1.2}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(A_{z;\bullet}\)</span> is an estimate of the reader population AUC mean (the bullet symbol replacing the reader index averages over a set of readers) for the fixed case-set <span class="math inline">\(\{1\}\)</span> and <span class="math inline">\(\sigma_{\text{br+wr}}^2\)</span> is the <em>between-reader plus within-reader</em> variance. The reason for adding the within-reader variance is explained in #3 below. The concept is that different groups of <span class="math inline">\(J\)</span> readers interpret the same case set <span class="math inline">\(\{1\}\)</span>, thereby sampling different parts of the reader distribution, causing fluctuations in the measured <span class="math inline">\(A_{z;j}\)</span> of the readers. Sometimes better readers are sampled and sometimes not so good ones are sampled. This time there is no “data compression” – each reader in the sample has an associated <span class="math inline">\(A_{z;j}\)</span>. However, variability of the average <span class="math inline">\(A_{z;\bullet}\)</span> over the <span class="math inline">\(J\)</span> readers is expected to decrease with increasing <span class="math inline">\(J\)</span>. This is the reason for seeking large reader-samples.</p>
<ol start="3" style="list-style-type: decimal">
<li>Consider a fixed reader, e.g., <span class="math inline">\(j = 1\)</span>, interpreting a fixed case-sample <span class="math inline">\(\{1\}\)</span>. Within-reader variability is due to variability of the ratings for the same case: the same reader interpreting the same case on different occasions will give different ratings to it, causing fluctuations in the measured AUC. This assumes that memory effects are minimized, for example, by sufficient time between successive interpretations as otherwise, if a case is shown twice in succession, the reader would give it the same rating each time. Since this is an intrinsic source of variability (analogous to the internal noise of a voltmeter) affecting each reader’s interpretations, it cannot be separated from case sampling variability, i.e., it cannot be “turned off”. The last sentence needs further explanation. A measurement of case-sampling variability requires a reader, and the reader comes with an intrinsic source of variability that gets added to the case-sampling variance, so what is measured is the sum of case sampling and within-reader variances, denoted <span class="math inline">\(\sigma_{\text{cs+wr}}^2\)</span>. Likewise, a measurement of between-reader variability requires a fixed case-set interpreted by different readers, each of whom comes with an intrinsic source of variability that gets added to the between-reader variance, yielding <span class="math inline">\(\sigma_{\text{br+wr}}^2\)</span>. To emphasize this point, an estimate of case-sampling variability <em>always</em> includes within reader variability. Likewise, an estimate of between-reader variability <em>always</em> includes within-reader variability.</li>
</ol>
<p>With this background, the purpose of this chapter is to delve into variability in some detail and in particular describe computational methods for estimating them. This chapter introduces the concept of resampling a dataset to estimate variability and the widely used bootstrap and jackknife methods of estimating variance are described. In a later chapter, these are extended to estimating covariance (essentially a scaled version of the correlation) between two random variables.</p>
<p>The starting point is the simplest scenario: a single reader interpreting a case-set.</p>
</div>
<div id="dependence-of-auc-on-the-case-sample" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.4</span> Dependence of AUC on the case sample<a href="sources-of-variability.html#dependence-of-auc-on-the-case-sample" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose a researcher conducts a ROC study with a single reader. The researcher starts by selecting a case-sample, i.e., a set of proven-truth non-diseased and diseased cases. Another researcher conducting another ROC study at the same institution selects a different case-sample, i.e., a different set of proven-truth non-diseased and diseased cases. The two case-sets contain the same numbers <span class="math inline">\(K_1,K_2\)</span> of non-diseased and diseased cases, respectively. Even if the same radiologist interprets the two case-sets, and the reader is perfectly reproducible, the AUC values are expected to be different. Therefore, AUC must depend on a case sample index, which is denoted <span class="math inline">\(\{c\}\)</span>, where <span class="math inline">\(c\)</span> is an integer: <span class="math inline">\(c = 1, 2\)</span>, as there are two case-sets in the study as envisaged.</p>
<p><span class="math display" id="eq:sources-of-variability-case-set">\[\begin{equation} 
AUC\rightarrow AUC_{\{c\}}
\tag{1.3}
\end{equation}\]</span></p>
<p>Note that <span class="math inline">\(\{c\}\)</span> is not an individual <em>case</em> index, rather it is a <em>case-set</em> index, i.e., different integer values of <span class="math inline">\(c\)</span> denote different sets, or samples, or groups, or collections of cases. [The dependence of AUC on the case sample index is not explicitly shown in the literature.]</p>
<p>What does the dependence of AUC on the <span class="math inline">\(c\)</span> index mean? Different case samples differ in their <em>difficulty</em> levels. A difficult case set contains a greater fraction of difficult cases than is usual. A difficult diseased case is one where disease is difficult to detect. For example, the lesions could be partly obscured by overlapping normal structures in the patient anatomy; i.e., the lesion does not “stick out”. Alternatively, variants of normal anatomy could mimic a lesion, like a blood vessel viewed end on in a chest radiograph, causing the radiologist to miss the real lesion(s) and mistake these blood vessels for lesions. An easy diseased case is one where the disease is easy to detect. For example, the lesion is projected over smooth background tissue, because of which it “sticks out”, or is more conspicuous2. How does difficulty level affect non-diseased cases? A difficult non-diseased case is one where variants of normal anatomy mimic actual lesions and could cause the radiologist to falsely diagnose the patient as diseased. Conversely, an easy non-diseased case is like a textbook illustration of normal anatomy. Every structure in it is clearly visualized and accounted for by the radiologist’s knowledge of the patient’s non-diseased anatomy, and the radiologist is confident that any abnormal structure, <em>if present</em>, would be readily seen. The radiologist is unlikely to falsely diagnose the patient as diseased. Difficult cases tend to be rated in the middle of the rating scale, while easy ones tend to be rated at the ends of the rating scale.</p>
<div id="case-sampling-variability-of-auc" class="section level3 hasAnchor">
<h3><span class="header-section-number">1.4.1</span> Case sampling variability of AUC<a href="sources-of-variability.html#case-sampling-variability-of-auc" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An easy case sample will cause AUC to increase over its average value; interpreting many case-sets and averaging the AUCs determines the average value. Conversely, a difficult case sample will cause AUC to decrease. Case sampling variability causes variability in the measured AUC. How does one estimate this essential source of variability? One method, totally impractical in the clinic but easy with simulations, is to have the same radiologist interpret repeated samples of case-sets from the population of cases (i.e., patients), termed <em>population sampling</em>, or more viscerally, as the “brute force” method.</p>
<p>Even if one could get a radiologist to interpret different case-sets, it is even more impractical to actually acquire the different case samples of truth-proven cases. Patients do not come conveniently labeled as non-diseased or diseased. Rather, one needs to follow-up on the patients, perhaps do other imaging tests, in order to establish true disease status, or ground-truth. In screening mammography, a woman who continues to be diagnosed as non-diseased on successive yearly screening tests in the US, and has no other symptoms of breast disease, is probably disease-free. Likewise, a woman diagnosed as diseased and the diagnosis is confirmed by biopsy (i.e., the biopsy comes back showing a malignancy in the sampled tissues) is known to be diseased. However, not all patients who are diseased are actually diagnosed as diseased: a typical false negative fraction is 20% in screening mammography3. This is where follow-up imaging can help determine true disease status at the initial screen. A false negative mistake is unlikely to be repeated at the next screen. After a year, the tumor may have grown, and is more likely to be detected. Having detected the tumor in the most recent screen, radiologists can go back and retrospectively view it in the initial screen, at which it was missed during the “live” interpretation. If one knows where to look, the cancer is easier to see. The previous screen images would be an example of a difficult diseased case. In unfortunate instances, the patient may die from the previously undetected cancer, which would establish the truth status at the initial screen, too late to do the patient any good. The process of determining actual truth is often referred to as defining the “gold standard”, the <em>ground truth</em>: or simply <em>truthing</em>.</p>
<p><em>One can appreciate from this discussion that acquiring independently proven cases, particularly diseased ones, is one of the most difficult aspects of conducting an observer performance study</em>.</p>
<p>There has to be a better way of estimating case-sampling variability. With a parametric model, the maximum likelihood procedure provides a means of estimating variability of each of the estimated parameters, which can be used to estimate the variability of <span class="math inline">\(A_z\)</span>, as in Chapter <code>TempComment \@ref(binormal-model)</code>. The estimate corresponds to case-sampling variability (including an inseparable within-reader variability). If unsure about this point, the reader should run some of the examples in Chapter <code>TempComment \@ref(binormal-model)</code> with increased numbers of cases. The variability is seen to decrease.</p>
<p>There are other options available for estimating case-sampling variance of AUC, and this chapter is not intended to be comprehensive. Three commonly used options are described: the DeLong et al method, the bootstrap and the jackknife resampling methods.</p>
</div>
</div>
<div id="sources-of-variabilityDeLong" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.5</span> DeLong method<a href="sources-of-variability.html#sources-of-variabilityDeLong" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If the figure-of-merit is the empirical AUC, then a procedure developed by DeLong et al4 (henceforth abbreviated to DeLong) is applicable that is based on earlier work by <span class="citation">(Noether <a href="#ref-RN2530" role="doc-biblioref">1967</a>)</span> and <span class="citation">(Bamber <a href="#ref-bamber1975area" role="doc-biblioref">1975</a>)</span>. The author will not go into details of this procedure but limit to showing that it “works”. However, before one can show that it “works”, one needs to know the true value of the variance of empirical AUC. Even if data were simulated using the binormal model, one cannot use the binormal model based estimate of variance as it is an estimate, not to be confused with a true value. Estimates are realizations of random numbers and are themselves subject to variability, which decreases with increasing case-set size. Instead, a “brute-force” (i.e., simulated population sampling) approach is adopted to determine the true value of the variance of AUC. The simulator provides a means of repeatedly generating case-sets interpreted by the same radiologist, and by sampling it enough time, e.g., <span class="math inline">\(C\)</span> = 10,000 times, each time calculating AUC, one determines the population mean and standard deviation. The standard deviation determined this way is compared to that yielded by the DeLong method to check if the latter actually works.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="sources-of-variability.html#cb1-1"></a>bruteForceEstimation &lt;-</span>
<span id="cb1-2"><a href="sources-of-variability.html#cb1-2"></a><span class="st">  </span><span class="cf">function</span>(seed, mu, sigma, K1, K2) {</span>
<span id="cb1-3"><a href="sources-of-variability.html#cb1-3"></a>    <span class="co"># brute force method to</span></span>
<span id="cb1-4"><a href="sources-of-variability.html#cb1-4"></a>    <span class="co"># find the population </span></span>
<span id="cb1-5"><a href="sources-of-variability.html#cb1-5"></a>    <span class="co"># meanempAuc and stdDevempAuc</span></span>
<span id="cb1-6"><a href="sources-of-variability.html#cb1-6"></a>    empAuc &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="dv">10000</span>)</span>
<span id="cb1-7"><a href="sources-of-variability.html#cb1-7"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(empAuc)) {</span>
<span id="cb1-8"><a href="sources-of-variability.html#cb1-8"></a>      zk1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K1)</span>
<span id="cb1-9"><a href="sources-of-variability.html#cb1-9"></a>      zk2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K2, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma)</span>
<span id="cb1-10"><a href="sources-of-variability.html#cb1-10"></a>      empAuc[i] &lt;-<span class="st"> </span><span class="kw">Wilcoxon</span>(zk1, zk2)</span>
<span id="cb1-11"><a href="sources-of-variability.html#cb1-11"></a>    }</span>
<span id="cb1-12"><a href="sources-of-variability.html#cb1-12"></a>    stdDevempAuc  &lt;-<span class="st">  </span><span class="kw">sqrt</span>(<span class="kw">var</span>(empAuc))</span>
<span id="cb1-13"><a href="sources-of-variability.html#cb1-13"></a>    meanempAuc   &lt;-<span class="st">  </span><span class="kw">mean</span>(empAuc)</span>
<span id="cb1-14"><a href="sources-of-variability.html#cb1-14"></a>    <span class="kw">return</span>(<span class="kw">list</span>(</span>
<span id="cb1-15"><a href="sources-of-variability.html#cb1-15"></a>      <span class="dt">meanempAuc =</span> meanempAuc,</span>
<span id="cb1-16"><a href="sources-of-variability.html#cb1-16"></a>      <span class="dt">stdDevempAuc =</span> stdDevempAuc</span>
<span id="cb1-17"><a href="sources-of-variability.html#cb1-17"></a>    ))</span>
<span id="cb1-18"><a href="sources-of-variability.html#cb1-18"></a>  }</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="sources-of-variability.html#cb2-1"></a>seed &lt;-<span class="st"> </span><span class="dv">1</span>;<span class="kw">set.seed</span>(seed)</span>
<span id="cb2-2"><a href="sources-of-variability.html#cb2-2"></a>mu &lt;-<span class="st"> </span><span class="fl">1.5</span>;sigma &lt;-<span class="st"> </span><span class="fl">1.3</span>;K1 &lt;-<span class="st"> </span><span class="dv">50</span>;K2 &lt;-<span class="st"> </span><span class="dv">52</span></span>
<span id="cb2-3"><a href="sources-of-variability.html#cb2-3"></a>ret &lt;-<span class="st"> </span><span class="kw">bruteForceEstimation</span>(seed, mu, sigma, K1, K2)</span>
<span id="cb2-4"><a href="sources-of-variability.html#cb2-4"></a><span class="co"># one more trial</span></span>
<span id="cb2-5"><a href="sources-of-variability.html#cb2-5"></a>zk1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K1)</span>
<span id="cb2-6"><a href="sources-of-variability.html#cb2-6"></a>zk2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K2, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma)</span>
<span id="cb2-7"><a href="sources-of-variability.html#cb2-7"></a>empAuc &lt;-<span class="st"> </span><span class="kw">Wilcoxon</span>(zk1, zk2)</span>
<span id="cb2-8"><a href="sources-of-variability.html#cb2-8"></a>ret1  &lt;-<span class="st"> </span><span class="kw">DeLongVar</span>(zk1,zk2)</span>
<span id="cb2-9"><a href="sources-of-variability.html#cb2-9"></a>stdDevDeLong &lt;-<span class="st"> </span><span class="kw">sqrt</span>(ret1)</span>
<span id="cb2-10"><a href="sources-of-variability.html#cb2-10"></a><span class="kw">cat</span>(<span class="st">&quot;brute force estimates:&quot;</span>,</span>
<span id="cb2-11"><a href="sources-of-variability.html#cb2-11"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">empAuc = &quot;</span>,</span>
<span id="cb2-12"><a href="sources-of-variability.html#cb2-12"></a>    ret<span class="op">$</span>meanempAuc,</span>
<span id="cb2-13"><a href="sources-of-variability.html#cb2-13"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">population standard deviation =&quot;</span>,</span>
<span id="cb2-14"><a href="sources-of-variability.html#cb2-14"></a>    ret<span class="op">$</span>stdDevempAuc, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb2-15"><a href="sources-of-variability.html#cb2-15"></a><span class="co">#&gt; brute force estimates: </span></span>
<span id="cb2-16"><a href="sources-of-variability.html#cb2-16"></a><span class="co">#&gt; empAuc =  0.819178 </span></span>
<span id="cb2-17"><a href="sources-of-variability.html#cb2-17"></a><span class="co">#&gt; population standard deviation = 0.04176683</span></span>
<span id="cb2-18"><a href="sources-of-variability.html#cb2-18"></a></span>
<span id="cb2-19"><a href="sources-of-variability.html#cb2-19"></a><span class="kw">cat</span>(<span class="st">&quot;single sample estimates = &quot;</span>,</span>
<span id="cb2-20"><a href="sources-of-variability.html#cb2-20"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">empirical AUC&quot;</span>,</span>
<span id="cb2-21"><a href="sources-of-variability.html#cb2-21"></a>    empAuc,</span>
<span id="cb2-22"><a href="sources-of-variability.html#cb2-22"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">standard deviation DeLong = &quot;</span>,</span>
<span id="cb2-23"><a href="sources-of-variability.html#cb2-23"></a>    stdDevDeLong, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb2-24"><a href="sources-of-variability.html#cb2-24"></a><span class="co">#&gt; single sample estimates =  </span></span>
<span id="cb2-25"><a href="sources-of-variability.html#cb2-25"></a><span class="co">#&gt; empirical AUC 0.8626923 </span></span>
<span id="cb2-26"><a href="sources-of-variability.html#cb2-26"></a><span class="co">#&gt; standard deviation DeLong =  0.03804135</span></span></code></pre></div>
<p>Two functions needed for this code to work are not shown: <code>Wilcoxon()</code> calculates the Wilcoxon statistic and the <code>DeLongVar()</code> implements the DeLong variance computation method (the DeLong method also calculates co-variances, but these are not needed in the current context). Line 1 sets the <code>seed</code> of the random number generator to 1. The <code>seed</code> variable is completely analogous to the case-set index <code>c</code>. Keeping <code>seed</code> fixed realizes the same random numbers each time the program is run. Different values of <code>seed</code> result in different, i.e., statistically independent, random samples. Line 2 initialize the values <span class="math inline">\((\mu, \sigma, K_1, K_2)\)</span> needed by the data simulator: the normal distributions are separated by <span class="math inline">\(\mu = 1.5\)</span>, the standard deviation of the diseased distribution is <span class="math inline">\(\sigma = 1.3\)</span>, and there are <span class="math inline">\(K_1 = 50\)</span> non-diseased and <span class="math inline">\(K_2 = 52\)</span> diseased cases. Line 3 calls <code>bruteForceEstimation</code>, the “brute force” method for estimating mean and standard deviation of the population distribution of AUC, returned by this function, which are the “correct” value to which the DeLong standard deviation estimate will be compared. Lines 4-9 generates a fresh ROC dataset to which the DeLong method is applied.</p>
<p>Two runs of this code were made, one with the smaller sample size, and the other with 10 times the sample size (the second run takes much longer). A third run was made with the larger sample size but with a different seed value. The results follow:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="sources-of-variability.html#cb3-1"></a>seed &lt;-<span class="st"> </span><span class="dv">2</span>;<span class="kw">set.seed</span>(seed)</span>
<span id="cb3-2"><a href="sources-of-variability.html#cb3-2"></a>mu &lt;-<span class="st"> </span><span class="fl">1.5</span>;sigma &lt;-<span class="st"> </span><span class="fl">1.3</span>;K1 &lt;-<span class="st"> </span><span class="dv">500</span>;K2 &lt;-<span class="st"> </span><span class="dv">520</span></span>
<span id="cb3-3"><a href="sources-of-variability.html#cb3-3"></a>ret &lt;-<span class="st"> </span><span class="kw">bruteForceEstimation</span>(seed, mu, sigma, K1, K2)</span>
<span id="cb3-4"><a href="sources-of-variability.html#cb3-4"></a><span class="co"># one more trial</span></span>
<span id="cb3-5"><a href="sources-of-variability.html#cb3-5"></a>zk1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K1)</span>
<span id="cb3-6"><a href="sources-of-variability.html#cb3-6"></a>zk2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(K2, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma)</span>
<span id="cb3-7"><a href="sources-of-variability.html#cb3-7"></a>empAuc &lt;-<span class="st"> </span><span class="kw">Wilcoxon</span>(zk1, zk2)</span>
<span id="cb3-8"><a href="sources-of-variability.html#cb3-8"></a>ret1  &lt;-<span class="st"> </span><span class="kw">DeLongVar</span>(zk1,zk2)</span>
<span id="cb3-9"><a href="sources-of-variability.html#cb3-9"></a>stdDevDeLong &lt;-<span class="st"> </span><span class="kw">sqrt</span>(ret1)</span>
<span id="cb3-10"><a href="sources-of-variability.html#cb3-10"></a><span class="kw">cat</span>(<span class="st">&quot;brute force estimates:&quot;</span>,</span>
<span id="cb3-11"><a href="sources-of-variability.html#cb3-11"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">empAuc = &quot;</span>,</span>
<span id="cb3-12"><a href="sources-of-variability.html#cb3-12"></a>    ret<span class="op">$</span>meanempAuc,</span>
<span id="cb3-13"><a href="sources-of-variability.html#cb3-13"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">population standard deviation =&quot;</span>,</span>
<span id="cb3-14"><a href="sources-of-variability.html#cb3-14"></a>    ret<span class="op">$</span>stdDevempAuc, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb3-15"><a href="sources-of-variability.html#cb3-15"></a><span class="co">#&gt; brute force estimates: </span></span>
<span id="cb3-16"><a href="sources-of-variability.html#cb3-16"></a><span class="co">#&gt; empAuc =  0.8194988 </span></span>
<span id="cb3-17"><a href="sources-of-variability.html#cb3-17"></a><span class="co">#&gt; population standard deviation = 0.01300203</span></span>
<span id="cb3-18"><a href="sources-of-variability.html#cb3-18"></a></span>
<span id="cb3-19"><a href="sources-of-variability.html#cb3-19"></a><span class="kw">cat</span>(<span class="st">&quot;single sample estimates = &quot;</span>,</span>
<span id="cb3-20"><a href="sources-of-variability.html#cb3-20"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">empirical AUC&quot;</span>,</span>
<span id="cb3-21"><a href="sources-of-variability.html#cb3-21"></a>    empAuc,</span>
<span id="cb3-22"><a href="sources-of-variability.html#cb3-22"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">standard deviation DeLong = &quot;</span>,</span>
<span id="cb3-23"><a href="sources-of-variability.html#cb3-23"></a>    stdDevDeLong, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb3-24"><a href="sources-of-variability.html#cb3-24"></a><span class="co">#&gt; single sample estimates =  </span></span>
<span id="cb3-25"><a href="sources-of-variability.html#cb3-25"></a><span class="co">#&gt; empirical AUC 0.8047269 </span></span>
<span id="cb3-26"><a href="sources-of-variability.html#cb3-26"></a><span class="co">#&gt; standard deviation DeLong =  0.01356696</span></span></code></pre></div>
<ol style="list-style-type: decimal">
<li>An important observation is that as sample-size increases, case-sampling variability decreases: 0.0417 for the smaller sample size vs. 0.01309 for the larger sample size, and the dependence is as the inverse square root of the numbers of cases, as expected from the central limit theorem.</li>
<li>With the smaller sample size (K1/K2 = 50/52; the back-slash notation, not to be confused with division, is a convenient way of summarizing the case-sample size) the estimated standard deviation (0.038) is within 10% of that estimated by population sampling (0.042). With the larger sample size, (K1/K2 = 500/520) the two are practically identical (0.01300203 vs. 0.01356696 – the latter value is for seed = 2).</li>
<li>Notice also that the one sample empirical AUC for the smaller case-size is 0.863, which is less than two standard deviations from the population mean 0.819. The “two standard deviations” comes from rounding up 1.96: as in Eqn. <code>TempComment \@ref(eq:binary-task-model-def-z-alpha2)</code>, where <span class="math inline">\(z_{\alpha/2}\)</span> was defined as the upper <span class="math inline">\(1-\alpha/2\)</span> quantile of the unit normal distribution and <span class="math inline">\(z_{0.025}=1.96\)</span>.</li>
<li>To reiterate, with clinical data the DeLong procedure estimates case sampling plus within reader variability. With simulated data as in this example, there is no within-reader variability as the simulator yields identical values for fixed seed.</li>
</ol>
<p>This demonstration should convince the reader that one does have recourse other than the “brute force” method, at least when the figure of merit is the empirical area under the ROC. That should come as a relief, as population sampling is impractical in the clinical context. It should also impress the reader, as the DeLong method is able to use information present in a <em>single dataset</em> to tease out its variability. [This is not magic: the MLE estimate is also able to tease out variability based on a parametric fit to a single dataset and examination of the sharpness of the peak of the log-likelihood function, Chapter <code>TempComment \@ref(binormal-model)</code>, as are the resampling methods described next.]</p>
<p>Next, two resampling–based methods of estimating case-sampling variance of AUC are introduced. The word “resampling” means that the dataset itself is regarded as containing information regarding its variability, which can be extracted by sampling from the original data (hence the word “resampling”). These are general and powerful techniques, applicable to any scalar statistic, not just the empirical AUC, which one might be able to use in other contexts.</p>
</div>
<div id="sources-of-variabilityBootstrap" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.6</span> Bootstrap method<a href="sources-of-variability.html#sources-of-variabilityBootstrap" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simplest resampling method, at least at the conceptual level, is the bootstrap. <em>The bootstrap method is based on the assumption that one can regard the observed sample as defining the population from which it was sampled.</em> Since by definition a population cannot be exhausted, the idea is to resample, <em>with replacement</em>, from the observed sample. Each resampling step realizes a particular bootstrap sample set denoted <span class="math inline">\(\{b\}\)</span>, where <span class="math inline">\(b = 1, 2, ..., B\)</span>. The curly brackets emphasize that different integer values of <span class="math inline">\(b\)</span> denote different <em>sets of cases</em>, not individual cases. [In contrast, the notation <span class="math inline">\((k)\)</span> will be used to denote <em>removing</em> a specific case, <span class="math inline">\(k\)</span>, as in the jackknife procedure to be described shortly. The index <span class="math inline">\(b\)</span> should not be confused with the index <span class="math inline">\(c\)</span>, the case sampling index; the latter denotes repeated sampling from the population, which is impractical in real life; the bootstrap index denotes repeated sampling from the dataset, which is quite feasible.] The procedure is repeated <span class="math inline">\(B\)</span> times, typically <span class="math inline">\(B\)</span> can be as small as 200, but to be safe I generally use about 1000 - 2000 bootstraps. The following example uses Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code> from Chapter <code>TempComment \@ref(ratings-paradigm)</code>.</p>
<p>For convenience, let us denote cases as follows. The 30 non-diseased cases that received the 1 rating are denoted <span class="math inline">\(k_{1,1},k_{2,1},...,k_{30,1}\)</span>. The second index denotes the truth state of the cases. Likewise, the 19 non-diseased cases that received the 2 rating are denoted <span class="math inline">\(k_{31,1},k_{32,1},...,k_{49,1}\)</span> and so on for the remaining non-diseased cases. The 5 diseased cases that received the 1 rating are denoted <span class="math inline">\(k_{1,2},k_{2,2},...,k_{5,2}\)</span>, the 6 diseased cases that received the 2 rating are denoted <span class="math inline">\(k_{6,2},k_{7,2},...,k_{11,2}\)</span>, and so on. Let us figuratively “put” all non-diseased cases (think of each case as an index card, with the case notation and rating recorded on it) into one hat (the non-diseased hat) and all the diseased cases into another hat (the diseased hat). Next, one randomly picks one case (card) from the non-diseased hat, records it’s rating, and puts the case back in the hat, so that it is free to be possibly picked again. This is repeated 60 times for the non-diseased hat resulting in 60 ratings from non-diseased cases. A similar procedure is performed using the diseased hat, resulting in 50 ratings from diseased cases. The author has just described, in painful detail (one might say) the realization of the 1st bootstrap sample, denoted <span class="math inline">\(\{b=1\}\)</span>. This is used to construct the 1st bootstrap counts table, Table <a href="sources-of-variability.html#tab:sources-of-variabilitybs1">1.1</a>.</p>
<table>
<caption>
<span id="tab:sources-of-variabilitybs1">TABLE 1.1: </span>Representative counts table.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
<span class="math inline">\(r = 5\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(r = 4\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(r = 3\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(r = 2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(r = 1\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
non-diseased
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
diseased
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
7
</td>
</tr>
</tbody>
</table>
<p>So what happened? Consider the 35 non-diseased cases with a 1 rating. If each non-diseased case rated 1 in Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code> were picked one time, the total would have been 30, but it is 35. Therefore, some of the original non-diseased cases rated 1 must have been picked multiple times, but one must also make allowance as there is no guarantee that a specific case was picked at all. Still focusing on the 35 non-diseased cases with a 1 rating in the first bootstrap sample, the picked labels, reordered after the fact, with respect to the first index, might be:</p>
<p><span class="math display" id="eq:sources-of-variabilitybs1-bs1-non-diseased">\[\begin{equation} 
k_{2,1},k_{2,1},k_{4,1},k_{4,1},k_{4,1},k_{6,1},k_{7,1},k_{7,1},k_{9,1},...,k_{28,1},k_{28,1},k_{30,1},k_{30,1}
\tag{1.4}
\end{equation}\]</span></p>
<p>In this example, case <span class="math inline">\(k_{1,1}\)</span> was not picked, case <span class="math inline">\(k_{2,1}\)</span> was picked twice, case <span class="math inline">\(k_{3,1}\)</span> was not picked, case <span class="math inline">\(k_{4,1}\)</span> was picked three times, case <span class="math inline">\(k_{5,1}\)</span> was not picked, case <span class="math inline">\(k_{6,1}\)</span> was picked once, etc. The total number of cases in Eqn. <a href="sources-of-variability.html#eq:sources-of-variabilitybs1-bs1-non-diseased">(1.4)</a> is 35, and similarly for the other cells in Table <a href="sources-of-variability.html#tab:sources-of-variabilitybs1">1.1</a>. Next, one estimates AUC for this table. Using the Eng website referred to earlier, one gets AUC = 0.843. [It is OK to use a parametric FOM since the bootstrap is a general procedure applicable, in principle, to any FOM, not just the empirical AUC, unlike the DeLong method, which is restricted to empirical AUC.] The corresponding value for the original data, Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>, was AUC = 0.870. The first bootstrapped dataset yielded a smaller value than the original dataset because one happened to have picked an unusually difficult bootstrap sample.</p>
<p>[Notice that in the original data there were 6 + 5 = 11 diseased cases that were rated 1 and 2, but in the bootstrapped dataset there are 7 + 9 = 16 diseased cases that were rated 1 and 2; in other words, the number of incorrect decisions on diseased cases went up, which would tend to lower AUC. Counteracting this effect is the increase in number of correct decisions on diseased cases: 8 + 19 = 27 cases rated 4 and 5, as compared to 12 + 22 = 34 in the original dataset. Reinforcing the effect is that increase in the number of correct decisions on non-diseased cases, albeit minimally: 35 + 16 = 51 rated 1 and 2 vs. 30 + 19 = 49 in the original dataset, and zero counts rated 4 and 5 in the non-diseased vs. 2 + 1 = 3 in the diseased. The complexity of following this <em>post-facto justification</em> illustrates the difficulty, in fact the futility, of correctly predicting which way performance will go from comparison of the two ROC counts tables – too many numbers are changing and in the above one did not even consider the change in counts in the bin labeled 4! Hence, the need for an objective figure of merit, such as the binormal model based AUC or the empirical AUC.]</p>
<p>To complete the description of the bootstrap method, one repeats the procedure described in the preceding paragraphs <span class="math inline">\(B = 200\)</span> times, each time running the website calculator and the final result is <span class="math inline">\(B\)</span> values of AUC, denoted:</p>
<p><span class="math display">\[AUC_{\{1\}},AUC_{\{2\}},...,AUC_{\{B\}}\]</span></p>
<p>where <span class="math inline">\(AUC_{\{1\}}=0.843\)</span>, etc. The bootstrap estimate of the variance of AUC is defined by <span class="citation">(Efron and Tibshirani <a href="#ref-RN2261" role="doc-biblioref">1993</a>)</span>:</p>
<p><span class="math display" id="eq:sources-of-variabilityVar-bs">\[\begin{equation} 
\text{Var}\left ( AUC \right )=\frac{1}{B-1}\sum_{b=1}^{B}\left ( AUC_{\{b\}}-AUC_{\{ \bullet\}} \right )^2
\tag{1.5}
\end{equation}\]</span></p>
<p>The right hand side is the traditional definition of (unbiased) variance. The dot represents the average over the <em>replaced index</em>. Of course, running the website code 200 times and recording the outputs is not a productive use of time. The following code implements two methods for estimating AUC, the empirical AUC, described in <code>TempComment Chapter \@ref(empirical-auc)</code> and the binormal model estimate of AUC, described in Chapter <code>TempComment \@ref(binormal-model)</code>.</p>
<div id="demonstration-of-the-bootstrap-method" class="section level3 hasAnchor">
<h3><span class="header-section-number">1.6.1</span> Demonstration of the bootstrap method<a href="sources-of-variability.html#demonstration-of-the-bootstrap-method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To minimize clutter, several <code>R</code> functions are not shown, but they are compiled. To display them <code>clone</code> or ‘fork’ the book repository and look at the <code>Rmd</code> file corresponding to this output and the sourced <code>R</code> files listed below:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="sources-of-variability.html#cb4-1"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/Transforms.R&quot;</span>))</span>
<span id="cb4-2"><a href="sources-of-variability.html#cb4-2"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/LL.R&quot;</span>))</span>
<span id="cb4-3"><a href="sources-of-variability.html#cb4-3"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/RocfitR.R&quot;</span>)) </span>
<span id="cb4-4"><a href="sources-of-variability.html#cb4-4"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/RocOperatingPoints.R&quot;</span>))</span>
<span id="cb4-5"><a href="sources-of-variability.html#cb4-5"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/FixRocCountsTable.R&quot;</span>))</span>
<span id="cb4-6"><a href="sources-of-variability.html#cb4-6"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/CH07-Variability/WilcoxonCountsTable.R&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="sources-of-variability.html#cb5-1"></a>doBootstrap &lt;-<span class="st"> </span><span class="cf">function</span>(parametricFOM, B, seed, RocTable) {</span>
<span id="cb5-2"><a href="sources-of-variability.html#cb5-2"></a>  <span class="co"># this is the K vector </span></span>
<span id="cb5-3"><a href="sources-of-variability.html#cb5-3"></a>  K &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">sum</span>(RocTable[<span class="dv">1</span>,]), <span class="kw">sum</span>(RocTable[<span class="dv">2</span>,]))</span>
<span id="cb5-4"><a href="sources-of-variability.html#cb5-4"></a>  </span>
<span id="cb5-5"><a href="sources-of-variability.html#cb5-5"></a>  <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb5-6"><a href="sources-of-variability.html#cb5-6"></a>    ret &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocTable)                 </span>
<span id="cb5-7"><a href="sources-of-variability.html#cb5-7"></a>  } <span class="cf">else</span> {</span>
<span id="cb5-8"><a href="sources-of-variability.html#cb5-8"></a>    ret &lt;-<span class="st"> </span><span class="kw">WilcoxonCountsTable</span>(RocTable) </span>
<span id="cb5-9"><a href="sources-of-variability.html#cb5-9"></a>  }</span>
<span id="cb5-10"><a href="sources-of-variability.html#cb5-10"></a>  OrigAUC  &lt;-<span class="st"> </span>ret<span class="op">$</span>AUC</span>
<span id="cb5-11"><a href="sources-of-variability.html#cb5-11"></a>  </span>
<span id="cb5-12"><a href="sources-of-variability.html#cb5-12"></a>  <span class="co"># ready to bootstrap</span></span>
<span id="cb5-13"><a href="sources-of-variability.html#cb5-13"></a>  <span class="co"># first put the counts data into a linear array</span></span>
<span id="cb5-14"><a href="sources-of-variability.html#cb5-14"></a>  <span class="co"># convert counts table to array</span></span>
<span id="cb5-15"><a href="sources-of-variability.html#cb5-15"></a>  z1  &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(RocTable[<span class="dv">1</span>,]),</span>
<span id="cb5-16"><a href="sources-of-variability.html#cb5-16"></a>             RocTable[<span class="dv">1</span>,])</span>
<span id="cb5-17"><a href="sources-of-variability.html#cb5-17"></a>  z2  &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(RocTable[<span class="dv">2</span>,]),</span>
<span id="cb5-18"><a href="sources-of-variability.html#cb5-18"></a>             RocTable[<span class="dv">2</span>,])<span class="co">#do:</span></span>
<span id="cb5-19"><a href="sources-of-variability.html#cb5-19"></a>  AUC &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> B)<span class="co">#to save the bs AUC values</span></span>
<span id="cb5-20"><a href="sources-of-variability.html#cb5-20"></a>  <span class="cf">for</span> ( b <span class="cf">in</span> <span class="dv">1</span> <span class="op">:</span><span class="st"> </span>B){</span>
<span id="cb5-21"><a href="sources-of-variability.html#cb5-21"></a>    <span class="cf">while</span> (<span class="dv">1</span>) {</span>
<span id="cb5-22"><a href="sources-of-variability.html#cb5-22"></a>      RocTable_bs  &lt;-<span class="st"> </span></span>
<span id="cb5-23"><a href="sources-of-variability.html#cb5-23"></a><span class="st">        </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="kw">length</span>(RocTable[<span class="dv">1</span>,])))</span>
<span id="cb5-24"><a href="sources-of-variability.html#cb5-24"></a>      <span class="co"># bs indices for non-diseased    </span></span>
<span id="cb5-25"><a href="sources-of-variability.html#cb5-25"></a>      k1_b &lt;-<span class="st"> </span><span class="kw">ceiling</span>( <span class="kw">runif</span>( K[ <span class="dv">1</span> ] ) <span class="op">*</span><span class="st"> </span>K[ <span class="dv">1</span> ] )</span>
<span id="cb5-26"><a href="sources-of-variability.html#cb5-26"></a>      <span class="co"># bs indices for diseased</span></span>
<span id="cb5-27"><a href="sources-of-variability.html#cb5-27"></a>      k2_b &lt;-<span class="st"> </span><span class="kw">ceiling</span>( <span class="kw">runif</span>( K[ <span class="dv">2</span> ] ) <span class="op">*</span><span class="st"> </span>K[ <span class="dv">2</span> ] )</span>
<span id="cb5-28"><a href="sources-of-variability.html#cb5-28"></a>      bsTable &lt;-<span class="st"> </span><span class="kw">table</span>(z1[k1_b])</span>
<span id="cb5-29"><a href="sources-of-variability.html#cb5-29"></a>      <span class="co">#convert array to frequency table</span></span>
<span id="cb5-30"><a href="sources-of-variability.html#cb5-30"></a>      RocTable_bs[<span class="dv">1</span>,<span class="kw">as.numeric</span>(<span class="kw">names</span>(bsTable))] &lt;-<span class="st"> </span></span>
<span id="cb5-31"><a href="sources-of-variability.html#cb5-31"></a><span class="st">        </span>bsTable</span>
<span id="cb5-32"><a href="sources-of-variability.html#cb5-32"></a>      bsTable &lt;-<span class="st"> </span><span class="kw">table</span>(z2[k2_b])</span>
<span id="cb5-33"><a href="sources-of-variability.html#cb5-33"></a>      <span class="co">#do:</span></span>
<span id="cb5-34"><a href="sources-of-variability.html#cb5-34"></a>      RocTable_bs[<span class="dv">2</span>,<span class="kw">as.numeric</span>(<span class="kw">names</span>(bsTable))] &lt;-<span class="st"> </span></span>
<span id="cb5-35"><a href="sources-of-variability.html#cb5-35"></a><span class="st">        </span>bsTable</span>
<span id="cb5-36"><a href="sources-of-variability.html#cb5-36"></a>      <span class="co">#replace NAs with zeroes</span></span>
<span id="cb5-37"><a href="sources-of-variability.html#cb5-37"></a>      RocTable_bs[<span class="kw">is.na</span>(RocTable_bs )] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb5-38"><a href="sources-of-variability.html#cb5-38"></a>      <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb5-39"><a href="sources-of-variability.html#cb5-39"></a>        temp &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocTable_bs)</span>
<span id="cb5-40"><a href="sources-of-variability.html#cb5-40"></a>      } <span class="cf">else</span> {</span>
<span id="cb5-41"><a href="sources-of-variability.html#cb5-41"></a>        temp &lt;-<span class="st"> </span><span class="kw">WilcoxonCountsTable</span>(RocTable_bs) </span>
<span id="cb5-42"><a href="sources-of-variability.html#cb5-42"></a>      }    </span>
<span id="cb5-43"><a href="sources-of-variability.html#cb5-43"></a>      AUC[b]  &lt;-<span class="st"> </span>temp<span class="op">$</span>AUC</span>
<span id="cb5-44"><a href="sources-of-variability.html#cb5-44"></a>      <span class="co"># a return of -1 means AUC did not converge</span></span>
<span id="cb5-45"><a href="sources-of-variability.html#cb5-45"></a>      <span class="cf">if</span> (AUC[b] <span class="op">!=</span><span class="st"> </span><span class="dv">-1</span>) <span class="cf">break</span></span>
<span id="cb5-46"><a href="sources-of-variability.html#cb5-46"></a>    }</span>
<span id="cb5-47"><a href="sources-of-variability.html#cb5-47"></a>  }</span>
<span id="cb5-48"><a href="sources-of-variability.html#cb5-48"></a>  meanAUCboot &lt;-<span class="st"> </span><span class="kw">mean</span>(AUC)</span>
<span id="cb5-49"><a href="sources-of-variability.html#cb5-49"></a>  Var &lt;-<span class="st"> </span><span class="kw">var</span>(AUC)</span>
<span id="cb5-50"><a href="sources-of-variability.html#cb5-50"></a>  stdAUCboot  &lt;-<span class="st"> </span><span class="kw">sqrt</span>(Var)</span>
<span id="cb5-51"><a href="sources-of-variability.html#cb5-51"></a>  <span class="kw">return</span>(<span class="kw">list</span>(</span>
<span id="cb5-52"><a href="sources-of-variability.html#cb5-52"></a>    <span class="dt">OrigAUC =</span> OrigAUC,</span>
<span id="cb5-53"><a href="sources-of-variability.html#cb5-53"></a>    <span class="dt">meanAUCboot =</span> meanAUCboot,</span>
<span id="cb5-54"><a href="sources-of-variability.html#cb5-54"></a>    <span class="dt">stdAUCboot =</span> stdAUCboot</span>
<span id="cb5-55"><a href="sources-of-variability.html#cb5-55"></a>  ))</span>
<span id="cb5-56"><a href="sources-of-variability.html#cb5-56"></a>}</span></code></pre></div>
<p>Since the bootstrap method is applicable to any scalar figure of merit, two options are provided in the code. If <code>parametricFOM</code> is set to <code>TRUE</code>, then the binormal model estimate is used, and if set to <code>FALSE</code>, the empirical AUC is used. The first set of results are obtained with <code>parametricFOM</code> set to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="sources-of-variability.html#cb6-1"></a>parametricFOM &lt;-<span class="st"> </span><span class="ot">TRUE</span></span>
<span id="cb6-2"><a href="sources-of-variability.html#cb6-2"></a>B &lt;-<span class="st"> </span><span class="dv">200</span>;seed &lt;-<span class="st"> </span><span class="dv">1</span>;<span class="kw">set.seed</span>(seed)</span>
<span id="cb6-3"><a href="sources-of-variability.html#cb6-3"></a>RocTable =<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb6-4"><a href="sources-of-variability.html#cb6-4"></a>RocTable[<span class="dv">1</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">19</span>,<span class="dv">8</span>,<span class="dv">2</span>,<span class="dv">1</span>)</span>
<span id="cb6-5"><a href="sources-of-variability.html#cb6-5"></a>RocTable[<span class="dv">2</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">12</span>,<span class="dv">22</span>)</span>
<span id="cb6-6"><a href="sources-of-variability.html#cb6-6"></a></span>
<span id="cb6-7"><a href="sources-of-variability.html#cb6-7"></a>ret &lt;-<span class="st"> </span><span class="kw">doBootstrap</span>(parametricFOM, B, seed, RocTable)</span>
<span id="cb6-8"><a href="sources-of-variability.html#cb6-8"></a>OrigAUC &lt;-<span class="st"> </span>ret<span class="op">$</span>OrigAUC</span>
<span id="cb6-9"><a href="sources-of-variability.html#cb6-9"></a>meanAUCboot &lt;-<span class="st"> </span>ret<span class="op">$</span>meanAUCboot</span>
<span id="cb6-10"><a href="sources-of-variability.html#cb6-10"></a>stdAUCboot &lt;-<span class="st"> </span>ret<span class="op">$</span>stdAUCboot</span>
<span id="cb6-11"><a href="sources-of-variability.html#cb6-11"></a></span>
<span id="cb6-12"><a href="sources-of-variability.html#cb6-12"></a><span class="kw">cat</span>(<span class="st">&quot;Bootstrap variance estimation:&quot;</span>,</span>
<span id="cb6-13"><a href="sources-of-variability.html#cb6-13"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">parametricFOM = &quot;</span>, parametricFOM,</span>
<span id="cb6-14"><a href="sources-of-variability.html#cb6-14"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">seed = &quot;</span>, seed, </span>
<span id="cb6-15"><a href="sources-of-variability.html#cb6-15"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">B = &quot;</span>, B,</span>
<span id="cb6-16"><a href="sources-of-variability.html#cb6-16"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">OrigAUC = &quot;</span>, OrigAUC, </span>
<span id="cb6-17"><a href="sources-of-variability.html#cb6-17"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">meanAUCboot = &quot;</span>, meanAUCboot, </span>
<span id="cb6-18"><a href="sources-of-variability.html#cb6-18"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">stdAUCboot = &quot;</span>, stdAUCboot, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb6-19"><a href="sources-of-variability.html#cb6-19"></a><span class="co">#&gt; Bootstrap variance estimation: </span></span>
<span id="cb6-20"><a href="sources-of-variability.html#cb6-20"></a><span class="co">#&gt; parametricFOM =  TRUE </span></span>
<span id="cb6-21"><a href="sources-of-variability.html#cb6-21"></a><span class="co">#&gt; seed =  1 </span></span>
<span id="cb6-22"><a href="sources-of-variability.html#cb6-22"></a><span class="co">#&gt; B =  200 </span></span>
<span id="cb6-23"><a href="sources-of-variability.html#cb6-23"></a><span class="co">#&gt; OrigAUC =  0.8704519 </span></span>
<span id="cb6-24"><a href="sources-of-variability.html#cb6-24"></a><span class="co">#&gt; meanAUCboot =  0.8671713 </span></span>
<span id="cb6-25"><a href="sources-of-variability.html#cb6-25"></a><span class="co">#&gt; stdAUCboot =  0.04380523</span></span></code></pre></div>
<p>This shows that the AUC of the original data (i.e., before performing any bootstrapping) is 0.870, the mean AUC of the B = 200 bootstrapped datasets is 0.867, and the standard deviation of the 200 bootstraps is 0.0438. If one runs the website calculator referenced in the previous chapter on the dataset shown in Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>, one finds that the MLE of the standard deviation of the AUC of the fitted ROC curve is 0.0378. The standard deviation is itself a statistic and there is sampling variability associated with it, i.e., there exists such a beast as a standard deviation of a standard deviation; the bootstrap estimate is not too far from the MLE estimate. By setting <code>seed</code> to different values, one gets an idea of the variability of the estimate of the standard deviation of AUC. For example, with <code>seed</code> = 2, one gets:</p>
<pre><code>#&gt; Bootstrap variance estimation: 
#&gt; parametricFOM =  TRUE 
#&gt; seed =  2 
#&gt; B =  200 
#&gt; OrigAUC =  0.8704519 
#&gt; meanAUCboot =  0.8673155 
#&gt; stdAUCboot =  0.03815402</code></pre>
<p>Note that both the mean of the bootstrap samples and the standard deviation have changed, but both are close to the MLE values. Examined next is the dependence of the estimates on <code>B</code>, the number of bootstraps. With <code>seed</code> = 1 and <code>B</code> = 2000 one gets:</p>
<pre><code>#&gt; Bootstrap variance estimation: 
#&gt; parametricFOM =  TRUE 
#&gt; seed =  1 
#&gt; B =  2000 
#&gt; OrigAUC =  0.8704519 
#&gt; meanAUCboot =  0.8674622 
#&gt; stdAUCboot =  0.03833508</code></pre>
<p>The estimates are evidently rather insensitive to <span class="math inline">\(B\)</span>, but the computation time was longer, ~13 seconds (running MLE 2000 times in 13 seconds is not bad!). It is always a good idea to test the stability of the results to different <span class="math inline">\(B\)</span> and <code>seed</code> values. Unlike the DeLong et al method, which is restricted to the Wilcoxon statistic (which equals empirical AUC as per the Bamber theorem), the bootstrap is broadly applicable to other figures of merit, including non-ROC paradigm figures of merit. However, beware that it depends on the assumption that the sample itself is representative of the population. With limited numbers of cases, this could be a bad assumption. [With small numbers of cases it is relatively easy to enumerate the different outcomes of the sampling process and, more importantly, their respective probabilities, leading to what is termed the <em>exact bootstrap</em>. It is “exact” in the sense that there is no seed variable or number of bootstrap dependence.]</p>
<p>Finally, here is the output when using non-parametric AUC, with <code>seed</code> = 1.</p>
<pre><code>#&gt; Bootstrap variance estimation: 
#&gt; parametricFOM =  FALSE 
#&gt; seed =  1 
#&gt; B =  200 
#&gt; OrigAUC =  0.8606667 
#&gt; meanAUCboot =  0.8604575 
#&gt; stdAUCboot =  0.04125475</code></pre>
</div>
</div>
<div id="sources-of-variabilityJackknife" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.7</span> Jackknife method<a href="sources-of-variability.html#sources-of-variabilityJackknife" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The second resampling method, termed the <em>jackknife</em>, is computationally less demanding, but as was seen with the bootstrap, with modern personal computers computational limitations are no longer that important, at least for the types of analyses that this book is concerned with.</p>
<p>In this method, the first case is removed, or jackknifed, from the set of cases and the MLE (or empirical estimation) is conducted on the resulting dataset, which has one less case. Let us denote by <span class="math inline">\(AUC_{(1)}\)</span> the resulting value of AUC. The parentheses around the subscript <span class="math inline">\(1\)</span> are meant to emphasize that the AUC value corresponds to that with the first case <em>removed</em> from the original dataset. Next, the first case is replaced, and now the second case is removed, the new dataset is analyzed yielding <span class="math inline">\(AUC_{(2)}\)</span>, and so on, yielding <span class="math inline">\(K\)</span> (<span class="math inline">\(K\)</span> is the total number of cases; <span class="math inline">\(K=K_1+K_2\)</span>) <em>jackknife AUC values</em>:</p>
<p><span class="math display" id="eq:sources-of-variabilityAUC-jackknife-fom">\[\begin{equation} 
AUC_{(k)} \qquad k=1,2,...,K
\tag{1.6}
\end{equation}\]</span></p>
<p>The corresponding jackknife pseudovalues <span class="math inline">\(Y_k\)</span> are defined by:</p>
<p><span class="math display" id="eq:sources-of-variability-pseudovalues-Y">\[\begin{equation} 
Y_k = K\times AUC - \left ( K-1 \right ) \times AUC_{(k)}
\tag{1.7}
\end{equation}\]</span></p>
<p>Here AUC denotes the estimate using the entire dataset, i.e., not removing any cases. The jackknife pseudovalues will turn out to be of central importance in TBA Chapter 09. The <em>jackknife AUC values</em>, defined by Eqn. <a href="sources-of-variability.html#eq:sources-of-variabilityAUC-jackknife-fom">(1.6)</a>, should not be confused with jackknife derived psuedovalues, defined by Eqn. <a href="sources-of-variability.html#eq:sources-of-variability-pseudovalues-Y">(1.7)</a>.</p>
<p>The jackknife estimate of the variance is defined by <span class="citation">(Efron and Tibshirani <a href="#ref-RN2261" role="doc-biblioref">1993</a>)</span>:</p>
<p><span class="math display" id="eq:sources-of-variability-jackknife-variance-definition">\[\begin{equation} 
\text{Var}_{\text{jack}} = \frac{\left ( K-1 \right )^2}{K} \frac{1}{K-1} \sum_{k=1}^{K} \left ( AUC_{(k)} - AUC_{(\bullet)} \right )^2
\tag{1.8}
\end{equation}\]</span></p>
<p>Since variance of <span class="math inline">\(K\)</span> scalars is defined by:</p>
<p><span class="math display" id="eq:sources-of-variability-variance-definition">\[\begin{equation} 
\text{Var}\left ( x \right ) = \frac{1}{K-1} \sum_{k=1}^{K} \left ( x_{k} - x_{\bullet} \right )^2
\tag{1.9}
\end{equation}\]</span></p>
<p>It follows that:</p>
<p><span class="math display" id="eq:sources-of-variability-jackknife-variance-ordinary-variance">\[\begin{equation} 
\text{Var}_{\text{jack}} \left ( \text{AUC} \right ) = \frac{\left ( K-1 \right )^2}{K} \text{Var} \left ( \text{AUC} \right )
\tag{1.10}
\end{equation}\]</span></p>
<p>In Eqn. <a href="sources-of-variability.html#eq:sources-of-variability-jackknife-variance-definition">(1.8)</a> I have deliberately not simplified the right hand side by canceling out <span class="math inline">\(K-1\)</span>. The purpose is to show, Eqn. <a href="sources-of-variability.html#eq:sources-of-variability-jackknife-variance-ordinary-variance">(1.10)</a>, that the usual expression for the variance (of the jackknife FOM values) needs to be multiplied by a <strong>variance inflation factor</strong> <span class="math inline">\(\frac{\left ( K-1 \right )^2}{K}\)</span>, which is approximately equal to <span class="math inline">\(K\)</span>, in order to obtain the correct jackknife estimate of variance of AUC. This factor was not necessary when one used the bootstrap method. That is because the bootstrap samples are more representative of the actual spread in the data. The jackknife samples are more restricted than the bootstrap samples, so the spread of the data is smaller; hence the need for the variance inflation factor <span class="citation">(Efron and Tibshirani <a href="#ref-RN2261" role="doc-biblioref">1993</a>)</span>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="sources-of-variability.html#cb10-1"></a>doJackknife &lt;-<span class="st"> </span><span class="cf">function</span>(parametricFOM, RocTable) {</span>
<span id="cb10-2"><a href="sources-of-variability.html#cb10-2"></a>  <span class="co"># this is the K vector </span></span>
<span id="cb10-3"><a href="sources-of-variability.html#cb10-3"></a>  K &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">sum</span>(RocTable[<span class="dv">1</span>,]), <span class="kw">sum</span>(RocTable[<span class="dv">2</span>,]))</span>
<span id="cb10-4"><a href="sources-of-variability.html#cb10-4"></a>  </span>
<span id="cb10-5"><a href="sources-of-variability.html#cb10-5"></a>  <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb10-6"><a href="sources-of-variability.html#cb10-6"></a>    ret &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocTable)                 </span>
<span id="cb10-7"><a href="sources-of-variability.html#cb10-7"></a>  } <span class="cf">else</span> {</span>
<span id="cb10-8"><a href="sources-of-variability.html#cb10-8"></a>    ret &lt;-<span class="st"> </span><span class="kw">WilcoxonCountsTable</span>(RocTable) </span>
<span id="cb10-9"><a href="sources-of-variability.html#cb10-9"></a>  }</span>
<span id="cb10-10"><a href="sources-of-variability.html#cb10-10"></a>  OrigAUC  &lt;-<span class="st"> </span>ret<span class="op">$</span>AUC</span>
<span id="cb10-11"><a href="sources-of-variability.html#cb10-11"></a>  </span>
<span id="cb10-12"><a href="sources-of-variability.html#cb10-12"></a>  <span class="co"># first put the counts data into a linear array</span></span>
<span id="cb10-13"><a href="sources-of-variability.html#cb10-13"></a>  z1  &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(RocTable[<span class="dv">1</span>,]),</span>
<span id="cb10-14"><a href="sources-of-variability.html#cb10-14"></a>             RocTable[<span class="dv">1</span>,])</span>
<span id="cb10-15"><a href="sources-of-variability.html#cb10-15"></a>  z2  &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(RocTable[<span class="dv">1</span>,]),</span>
<span id="cb10-16"><a href="sources-of-variability.html#cb10-16"></a>             RocTable[<span class="dv">2</span>,])</span>
<span id="cb10-17"><a href="sources-of-variability.html#cb10-17"></a>  </span>
<span id="cb10-18"><a href="sources-of-variability.html#cb10-18"></a>  AUC_jack  &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">sum</span>(K))</span>
<span id="cb10-19"><a href="sources-of-variability.html#cb10-19"></a>  Y_k &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">sum</span>(K))</span>
<span id="cb10-20"><a href="sources-of-variability.html#cb10-20"></a>  z_jk  &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">sum</span>(K))</span>
<span id="cb10-21"><a href="sources-of-variability.html#cb10-21"></a>  <span class="co"># ready to jackknife</span></span>
<span id="cb10-22"><a href="sources-of-variability.html#cb10-22"></a>  <span class="cf">for</span> ( k <span class="cf">in</span> <span class="dv">1</span> <span class="op">:</span><span class="st"> </span><span class="kw">sum</span>(K)){</span>
<span id="cb10-23"><a href="sources-of-variability.html#cb10-23"></a>    RocTable_jk  &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="kw">length</span>(RocTable[<span class="dv">1</span>,])))</span>
<span id="cb10-24"><a href="sources-of-variability.html#cb10-24"></a>    <span class="cf">if</span> ( k <span class="op">&lt;=</span><span class="st"> </span>K[ <span class="dv">1</span> ]){</span>
<span id="cb10-25"><a href="sources-of-variability.html#cb10-25"></a>      z1_jk &lt;-<span class="st"> </span>z1[ <span class="op">-</span>k ]</span>
<span id="cb10-26"><a href="sources-of-variability.html#cb10-26"></a>      z2_jk &lt;-<span class="st"> </span>z2</span>
<span id="cb10-27"><a href="sources-of-variability.html#cb10-27"></a>    }<span class="cf">else</span>{</span>
<span id="cb10-28"><a href="sources-of-variability.html#cb10-28"></a>      z1_jk &lt;-<span class="st"> </span>z1</span>
<span id="cb10-29"><a href="sources-of-variability.html#cb10-29"></a>      z2_jk &lt;-<span class="st"> </span>z2[ <span class="op">-</span>(k <span class="op">-</span><span class="st"> </span>K[ <span class="dv">1</span> ]) ] </span>
<span id="cb10-30"><a href="sources-of-variability.html#cb10-30"></a>    }  </span>
<span id="cb10-31"><a href="sources-of-variability.html#cb10-31"></a>    <span class="co">#convert array to frequency table</span></span>
<span id="cb10-32"><a href="sources-of-variability.html#cb10-32"></a>    RocTable_jk[<span class="dv">1</span>,<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(<span class="kw">table</span>(z1_jk))]  &lt;-<span class="st"> </span></span>
<span id="cb10-33"><a href="sources-of-variability.html#cb10-33"></a><span class="st">      </span><span class="kw">table</span>(z1_jk)</span>
<span id="cb10-34"><a href="sources-of-variability.html#cb10-34"></a>    RocTable_jk[<span class="dv">2</span>,<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(<span class="kw">table</span>(z2_jk))]  &lt;-<span class="st"> </span></span>
<span id="cb10-35"><a href="sources-of-variability.html#cb10-35"></a><span class="st">      </span><span class="kw">table</span>(z2_jk)</span>
<span id="cb10-36"><a href="sources-of-variability.html#cb10-36"></a>    <span class="co">#replace NAs with zeroes</span></span>
<span id="cb10-37"><a href="sources-of-variability.html#cb10-37"></a>    RocTable_jk[<span class="kw">is.na</span>(RocTable_jk)] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb10-38"><a href="sources-of-variability.html#cb10-38"></a>    <span class="co"># AUC_jack for observed data</span></span>
<span id="cb10-39"><a href="sources-of-variability.html#cb10-39"></a>    <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb10-40"><a href="sources-of-variability.html#cb10-40"></a>      temp &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocTable_jk) </span>
<span id="cb10-41"><a href="sources-of-variability.html#cb10-41"></a>    } <span class="cf">else</span> {</span>
<span id="cb10-42"><a href="sources-of-variability.html#cb10-42"></a>      temp &lt;-<span class="st"> </span><span class="kw">WilcoxonCountsTable</span>(RocTable_jk) </span>
<span id="cb10-43"><a href="sources-of-variability.html#cb10-43"></a>    }      </span>
<span id="cb10-44"><a href="sources-of-variability.html#cb10-44"></a>    AUC_jack[k]  &lt;-<span class="st"> </span>temp<span class="op">$</span>AUC</span>
<span id="cb10-45"><a href="sources-of-variability.html#cb10-45"></a>    Y_k[k] &lt;-<span class="st"> </span><span class="kw">sum</span>(K)<span class="op">*</span>OrigAUC <span class="op">-</span><span class="st"> </span>(<span class="kw">sum</span>(K)<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>AUC_jack[k]</span>
<span id="cb10-46"><a href="sources-of-variability.html#cb10-46"></a>    <span class="cf">if</span> (AUC_jack[k] <span class="op">==</span><span class="st"> </span><span class="dv">-1</span>) </span>
<span id="cb10-47"><a href="sources-of-variability.html#cb10-47"></a>      <span class="kw">stop</span>(<span class="st">&quot;RocfitR did not converge in jackknife loop&quot;</span>) </span>
<span id="cb10-48"><a href="sources-of-variability.html#cb10-48"></a>  }</span>
<span id="cb10-49"><a href="sources-of-variability.html#cb10-49"></a>  meanAUCjack &lt;-<span class="st"> </span><span class="kw">mean</span>(AUC_jack)</span>
<span id="cb10-50"><a href="sources-of-variability.html#cb10-50"></a>  <span class="co">#Efron and Stein&#39;s paper, include jackknife inflation factor</span></span>
<span id="cb10-51"><a href="sources-of-variability.html#cb10-51"></a>  Var_jack &lt;-<span class="st"> </span><span class="kw">var</span>(AUC_jack) <span class="op">*</span><span class="st"> </span>( <span class="kw">sum</span>(K) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)<span class="op">^</span><span class="dv">2</span> <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(K) </span>
<span id="cb10-52"><a href="sources-of-variability.html#cb10-52"></a>  stdAUCjack  &lt;-<span class="st"> </span><span class="kw">sqrt</span>(Var_jack)</span>
<span id="cb10-53"><a href="sources-of-variability.html#cb10-53"></a>  <span class="kw">return</span>(<span class="kw">list</span>(</span>
<span id="cb10-54"><a href="sources-of-variability.html#cb10-54"></a>    <span class="dt">OrigAUC =</span> OrigAUC,</span>
<span id="cb10-55"><a href="sources-of-variability.html#cb10-55"></a>    <span class="dt">meanAUCjack =</span> meanAUCjack,</span>
<span id="cb10-56"><a href="sources-of-variability.html#cb10-56"></a>    <span class="dt">stdAUCjack =</span> stdAUCjack</span>
<span id="cb10-57"><a href="sources-of-variability.html#cb10-57"></a>  ))</span>
<span id="cb10-58"><a href="sources-of-variability.html#cb10-58"></a>}</span></code></pre></div>
<p>Since the jackknife method is applicable to any scalar figure of merit, two options are provided in the code. If <code>parametricFOM</code> is set to <code>TRUE</code>, then the binormal model estimate is used, and if set to <code>FALSE</code>, the empirical AUC is used. The first set of results are obtained with <code>parametricFOM</code> set to <code>TRUE</code>. Notice that the code does not use a <code>set.seed()</code> statement, as no random number generator is needed in the jackknife method. Systematically removing and replacing each case in sequence, one at a time, is not random sampling, which should further explain the need for the variance inflation factor in Eqn. <a href="sources-of-variability.html#eq:sources-of-variability-jackknife-variance-ordinary-variance">(1.10)</a>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="sources-of-variability.html#cb11-1"></a>parametricFOM &lt;-<span class="st"> </span><span class="ot">TRUE</span></span>
<span id="cb11-2"><a href="sources-of-variability.html#cb11-2"></a>RocTable =<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb11-3"><a href="sources-of-variability.html#cb11-3"></a>RocTable[<span class="dv">1</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">19</span>,<span class="dv">8</span>,<span class="dv">2</span>,<span class="dv">1</span>)</span>
<span id="cb11-4"><a href="sources-of-variability.html#cb11-4"></a>RocTable[<span class="dv">2</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">12</span>,<span class="dv">22</span>)</span>
<span id="cb11-5"><a href="sources-of-variability.html#cb11-5"></a></span>
<span id="cb11-6"><a href="sources-of-variability.html#cb11-6"></a>ret &lt;-<span class="st"> </span><span class="kw">doJackknife</span>(parametricFOM, RocTable)</span>
<span id="cb11-7"><a href="sources-of-variability.html#cb11-7"></a>OrigAUC &lt;-<span class="st"> </span>ret<span class="op">$</span>OrigAUC</span>
<span id="cb11-8"><a href="sources-of-variability.html#cb11-8"></a>meanAUCjack &lt;-<span class="st"> </span>ret<span class="op">$</span>meanAUCjack</span>
<span id="cb11-9"><a href="sources-of-variability.html#cb11-9"></a>stdAUCjack &lt;-<span class="st"> </span>ret<span class="op">$</span>stdAUCjack</span>
<span id="cb11-10"><a href="sources-of-variability.html#cb11-10"></a></span>
<span id="cb11-11"><a href="sources-of-variability.html#cb11-11"></a><span class="kw">cat</span>(<span class="st">&quot;Jackknife variance estimation:&quot;</span>,</span>
<span id="cb11-12"><a href="sources-of-variability.html#cb11-12"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">parametricFOM = &quot;</span>, parametricFOM,</span>
<span id="cb11-13"><a href="sources-of-variability.html#cb11-13"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">OrigAUC = &quot;</span>, OrigAUC, </span>
<span id="cb11-14"><a href="sources-of-variability.html#cb11-14"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">meanAUCjack = &quot;</span>, meanAUCjack, </span>
<span id="cb11-15"><a href="sources-of-variability.html#cb11-15"></a>    <span class="st">&quot;</span><span class="ch">\n</span><span class="st">stdAUCjack = &quot;</span>, stdAUCjack, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb11-16"><a href="sources-of-variability.html#cb11-16"></a><span class="co">#&gt; Jackknife variance estimation: </span></span>
<span id="cb11-17"><a href="sources-of-variability.html#cb11-17"></a><span class="co">#&gt; parametricFOM =  TRUE </span></span>
<span id="cb11-18"><a href="sources-of-variability.html#cb11-18"></a><span class="co">#&gt; OrigAUC =  0.8704519 </span></span>
<span id="cb11-19"><a href="sources-of-variability.html#cb11-19"></a><span class="co">#&gt; meanAUCjack =  0.8704304 </span></span>
<span id="cb11-20"><a href="sources-of-variability.html#cb11-20"></a><span class="co">#&gt; stdAUCjack =  0.03861591</span></span></code></pre></div>
<p>The next output is with the non-parametric figure of merit:</p>
<pre><code>#&gt; Jackknife variance estimation: 
#&gt; parametricFOM =  FALSE 
#&gt; OrigAUC =  0.8606667 
#&gt; meanAUCjack =  0.8606667 
#&gt; stdAUCjack =  0.03689264</code></pre>
<p>It may be noticed that the mean of the jackknife figure of merit values, i.e., 0.8606667, exactly equals the original figure of merit 0.8606667 (i.e., that calculated including all cases). This can be shown analytically to be true so long as the figure of merit is the empirical AUC. A similar relation is not true for the bootstrap.</p>
</div>
<div id="sources-of-variabilityCalSimulator" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.8</span> Calibrated simulator<a href="sources-of-variability.html#sources-of-variabilityCalSimulator" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="the-need-for-a-calibrated-simulator" class="section level3 hasAnchor">
<h3><span class="header-section-number">1.8.1</span> The need for a calibrated simulator<a href="sources-of-variability.html#the-need-for-a-calibrated-simulator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The population sampling method used previously, <a href="sources-of-variability.html#sources-of-variabilityDeLong">1.5</a>, to compare the DeLong method to a known standard used arbitrarily set simulator values, i.e., <span class="math inline">\(\mu = 1.5\)</span> and <span class="math inline">\(\sigma = 1.3\)</span>. One does not know if these values actually represent real clinical data. In this section a simple method of implementing population sampling using a <em>calibrated simulator</em> is described. A calibrated simulator is one whose parameters are chosen to match those of an actual clinical dataset. This way one has some assurance that the simulator is realistic and therefore its verdict on a proposed method or analysis (in our case method of estimating AUC variability) is likely to be correct.</p>
</div>
<div id="implementation-of-a-simple-calibrated-simulator" class="section level3 hasAnchor">
<h3><span class="header-section-number">1.8.2</span> Implementation of a simple calibrated simulator<a href="sources-of-variability.html#implementation-of-a-simple-calibrated-simulator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The simple simulator described here is limited to a single reader single modality dataset. A more complex simulator describing multiple readers in multiple modalities is described in a later chapter (TBA). Consider a clinical dataset, such as in Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>. Analyzed by MLE, this yields binormal model parameters, <code>a</code>, <code>b</code> and the thresholds <span class="math inline">\(\zeta_1,\zeta_2,\zeta_3,\zeta_4\)</span>. After conversion to <span class="math inline">\(\mu=a/b\)</span> and <span class="math inline">\(\sigma= 1/b\)</span> and new zetas <span class="math inline">\(\zeta = \zeta/b\)</span>, the values are (in the same order): 2.173597, 1.646099, 0.01263423, 1.475351, 2.494901, 3.945221 (see code output below):</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="sources-of-variability.html#cb13-1"></a><span class="co"># mu_sigma is the mu-sigma notation</span></span>
<span id="cb13-2"><a href="sources-of-variability.html#cb13-2"></a>mu_sigma &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">2.173597</span>, <span class="fl">1.646099</span>, <span class="fl">0.01263423</span>, <span class="fl">1.475351</span>, <span class="fl">2.494901</span>, <span class="fl">3.945221</span>)</span>
<span id="cb13-3"><a href="sources-of-variability.html#cb13-3"></a><span class="co"># ab is the a-b notation</span></span>
<span id="cb13-4"><a href="sources-of-variability.html#cb13-4"></a>ab &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.320453</span>, <span class="fl">0.607497</span>, <span class="fl">0.007675259</span>, <span class="fl">0.8962713</span>, <span class="fl">1.515645</span>, <span class="fl">2.39671</span>)</span>
<span id="cb13-5"><a href="sources-of-variability.html#cb13-5"></a>ab[<span class="dv">1</span>]<span class="op">/</span>ab[<span class="dv">2</span>] <span class="co"># this is mu</span></span>
<span id="cb13-6"><a href="sources-of-variability.html#cb13-6"></a><span class="co">#&gt; [1] 2.173596</span></span>
<span id="cb13-7"><a href="sources-of-variability.html#cb13-7"></a><span class="dv">1</span><span class="op">/</span>ab[<span class="dv">2</span>]    <span class="co"># this is sigma</span></span>
<span id="cb13-8"><a href="sources-of-variability.html#cb13-8"></a><span class="co">#&gt; [1] 1.646099</span></span>
<span id="cb13-9"><a href="sources-of-variability.html#cb13-9"></a>ab[<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]<span class="op">/</span>ab[<span class="dv">2</span>] <span class="co"># this is zeta in mu-sigma notation</span></span>
<span id="cb13-10"><a href="sources-of-variability.html#cb13-10"></a><span class="co">#&gt; [1] 0.01263423 1.47535099 2.49490121 3.94522113</span></span></code></pre></div>
<p>[The reason for dividing <span class="math inline">\(\zeta\)</span> by <span class="math inline">\(b\)</span> is that when re-scaling the decision variable axis by <span class="math inline">\(b\)</span> one must also re-scale the cutoffs.] The values <span class="math inline">\(\mu,\sigma,\zeta\)</span> define the calibrated simulator, in the sense that the parameter values are calibrated to match the dataset in Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>.</p>
<p>Here is the function <code>doCalSimulator()</code> that will be used to perform the initial calibration followed by population sampling from the calibrated simulator:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb14-1"><a href="sources-of-variability.html#cb14-1"></a>doCalSimulator &lt;-<span class="st"> </span><span class="cf">function</span>(P, parametricFOM, RocCountsTable) {</span>
<span id="cb14-2"><a href="sources-of-variability.html#cb14-2"></a>  K &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">sum</span>(RocCountsTable[<span class="dv">1</span>,]), </span>
<span id="cb14-3"><a href="sources-of-variability.html#cb14-3"></a>         <span class="kw">sum</span>(RocCountsTable[<span class="dv">2</span>,]))</span>
<span id="cb14-4"><a href="sources-of-variability.html#cb14-4"></a>  <span class="co"># perform the initial calibration</span></span>
<span id="cb14-5"><a href="sources-of-variability.html#cb14-5"></a>  ret &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocCountsTable) <span class="co"># AUC for observed data</span></span>
<span id="cb14-6"><a href="sources-of-variability.html#cb14-6"></a>  a &lt;-<span class="st"> </span>ret<span class="op">$</span>a</span>
<span id="cb14-7"><a href="sources-of-variability.html#cb14-7"></a>  b  &lt;-<span class="st"> </span>ret<span class="op">$</span>b</span>
<span id="cb14-8"><a href="sources-of-variability.html#cb14-8"></a>  zetas &lt;-<span class="st"> </span>ret<span class="op">$</span>zeta</span>
<span id="cb14-9"><a href="sources-of-variability.html#cb14-9"></a>  mu  &lt;-<span class="st"> </span>a<span class="op">/</span>b</span>
<span id="cb14-10"><a href="sources-of-variability.html#cb14-10"></a>  sigma &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span>b</span>
<span id="cb14-11"><a href="sources-of-variability.html#cb14-11"></a>  zetas &lt;-<span class="st"> </span>zetas<span class="op">/</span>b <span class="co"># need to also scale zetas</span></span>
<span id="cb14-12"><a href="sources-of-variability.html#cb14-12"></a>   <span class="co"># AUC for observed data</span></span>
<span id="cb14-13"><a href="sources-of-variability.html#cb14-13"></a>  <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb14-14"><a href="sources-of-variability.html#cb14-14"></a>    OrigAUC &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocCountsTable)<span class="op">$</span>AUC                 </span>
<span id="cb14-15"><a href="sources-of-variability.html#cb14-15"></a>  } <span class="cf">else</span> {</span>
<span id="cb14-16"><a href="sources-of-variability.html#cb14-16"></a>    OrigAUC &lt;-<span class="st"> </span><span class="kw">WilcoxonCountsTable</span>(RocCountsTable)<span class="op">$</span>AUC </span>
<span id="cb14-17"><a href="sources-of-variability.html#cb14-17"></a>  }</span>
<span id="cb14-18"><a href="sources-of-variability.html#cb14-18"></a>  <span class="co"># perform the population sampling</span></span>
<span id="cb14-19"><a href="sources-of-variability.html#cb14-19"></a>  AUC &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> P)</span>
<span id="cb14-20"><a href="sources-of-variability.html#cb14-20"></a>  <span class="cf">for</span> ( p <span class="cf">in</span> <span class="dv">1</span> <span class="op">:</span><span class="st"> </span>P){</span>
<span id="cb14-21"><a href="sources-of-variability.html#cb14-21"></a>    <span class="cf">while</span> (<span class="dv">1</span>) {</span>
<span id="cb14-22"><a href="sources-of-variability.html#cb14-22"></a>      </span>
<span id="cb14-23"><a href="sources-of-variability.html#cb14-23"></a>      RocCountsTableSimPop &lt;-<span class="st"> </span></span>
<span id="cb14-24"><a href="sources-of-variability.html#cb14-24"></a><span class="st">        </span><span class="kw">SimulateRocCountsTable</span>(K, mu, sigma, zetas)</span>
<span id="cb14-25"><a href="sources-of-variability.html#cb14-25"></a>      <span class="cf">if</span> (parametricFOM) {</span>
<span id="cb14-26"><a href="sources-of-variability.html#cb14-26"></a>        </span>
<span id="cb14-27"><a href="sources-of-variability.html#cb14-27"></a>        <span class="co"># AUC for fitted curve </span></span>
<span id="cb14-28"><a href="sources-of-variability.html#cb14-28"></a>        temp &lt;-<span class="st"> </span><span class="kw">RocfitR</span>(RocCountsTableSimPop)</span>
<span id="cb14-29"><a href="sources-of-variability.html#cb14-29"></a>        <span class="co"># a return of -1 means RocFitR did not converge</span></span>
<span id="cb14-30"><a href="sources-of-variability.html#cb14-30"></a>        <span class="cf">if</span> (temp[<span class="dv">1</span>] <span class="op">!=</span><span class="st"> </span><span class="dv">-1</span>) {</span>
<span id="cb14-31"><a href="sources-of-variability.html#cb14-31"></a>          AUC[p]  &lt;-<span class="st"> </span>temp<span class="op">$</span>AUC</span>
<span id="cb14-32"><a href="sources-of-variability.html#cb14-32"></a>          <span class="cf">break</span> </span>
<span id="cb14-33"><a href="sources-of-variability.html#cb14-33"></a>        }</span>
<span id="cb14-34"><a href="sources-of-variability.html#cb14-34"></a>      } <span class="cf">else</span> {</span>
<span id="cb14-35"><a href="sources-of-variability.html#cb14-35"></a>        AUC[p] &lt;-<span class="st"> </span>(<span class="kw">WilcoxonCountsTable</span>(RocCountsTableSimPop))<span class="op">$</span>AUC</span>
<span id="cb14-36"><a href="sources-of-variability.html#cb14-36"></a>        <span class="cf">break</span> </span>
<span id="cb14-37"><a href="sources-of-variability.html#cb14-37"></a>      }    </span>
<span id="cb14-38"><a href="sources-of-variability.html#cb14-38"></a>    }</span>
<span id="cb14-39"><a href="sources-of-variability.html#cb14-39"></a>  }</span>
<span id="cb14-40"><a href="sources-of-variability.html#cb14-40"></a>  AUC &lt;-<span class="st"> </span>AUC[<span class="op">!</span><span class="kw">is.na</span>(AUC)]</span>
<span id="cb14-41"><a href="sources-of-variability.html#cb14-41"></a>  meanAUC  &lt;-<span class="st"> </span><span class="kw">mean</span>(AUC)</span>
<span id="cb14-42"><a href="sources-of-variability.html#cb14-42"></a>  stdAUC  &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">var</span>(AUC))</span>
<span id="cb14-43"><a href="sources-of-variability.html#cb14-43"></a>  <span class="kw">return</span>(<span class="kw">list</span>(</span>
<span id="cb14-44"><a href="sources-of-variability.html#cb14-44"></a>    <span class="dt">mu =</span> mu, <span class="co"># these define the calibration simulator</span></span>
<span id="cb14-45"><a href="sources-of-variability.html#cb14-45"></a>    <span class="dt">sigma =</span> sigma, <span class="co">#do:</span></span>
<span id="cb14-46"><a href="sources-of-variability.html#cb14-46"></a>    <span class="dt">zetas =</span> zetas, <span class="co">#do:</span></span>
<span id="cb14-47"><a href="sources-of-variability.html#cb14-47"></a>    <span class="dt">OrigAUC =</span> OrigAUC,</span>
<span id="cb14-48"><a href="sources-of-variability.html#cb14-48"></a>    <span class="dt">meanAUC =</span> meanAUC,</span>
<span id="cb14-49"><a href="sources-of-variability.html#cb14-49"></a>    <span class="dt">stdAUC =</span> stdAUC</span>
<span id="cb14-50"><a href="sources-of-variability.html#cb14-50"></a>  ))</span>
<span id="cb14-51"><a href="sources-of-variability.html#cb14-51"></a>}</span></code></pre></div>
<p>In the function <code>doCalSimulator(P, parametricFOM, RocCountsTable)</code>, <code>P</code> is the desired number of population samples, <code>parametricFOM</code> is a logical, if set to <code>TRUE</code> the binormal model is used to calculate <em>fitted</em> AUC and otherwise the Wilcoxon statistic is used to calculate <em>empirical</em> AUC, and <code>RocCountsTable</code> contains the ROC data, such as Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>, to which the simulator is to be calibrated to. Lines 2-3 construct the K-vector, containing <span class="math inline">\(K_1,K_2\)</span>. Line 5 performs the maximum likelihood fit, using function <code>RocfitR(RocCountsTable)</code>. The returned variable contains <span class="math inline">\(a, b, \zeta\)</span> as a <code>list</code>, which are extracted at lines 6-8. Lines 9-11 converts these to the mu-sigma notation. In essence, lines 5 - 11 calibrates the simulator and the calibrated values of the simulator are contained in <span class="math inline">\(\mu,\sigma,\zeta\)</span>. Lines 13-17 calculates <code>OrigAUC</code>, the AUC of the original data, using parametric <code>RocfitR</code> or the Wilcoxon statistic, as appropriate, depending on the value of <code>parametricFOM</code>. After defining a length <code>P</code> array, at line 19, to hold the sampled <code>AUC</code> values, lines 20-39 begins and ends a <code>for</code> loop to conduct the <code>P</code> population samples. Each pass through the <code>for</code> loop yields <span class="math inline">\(K_1\)</span> samples from the non-diseased distribution and <span class="math inline">\(K_2\)</span> samples from the diseased distribution, returned in the variable <code>RocCountsTableSimPop</code>, which is similar in structure to a counts table like Table <code>TempComment \@ref(tab:ratings-paradigm-example-table)</code>. Within the <code>for</code> loop there is an endless <code>while</code> loop, needed because <code>RocfitR</code> can sometimes fail to converge, signaled by the first member of the returned <code>list</code> being minus 1, in which case another iteration of the <code>while</code> loop is performed (see line 30) and otherwise the <code>break</code> statement (line 32) causes program execution to proceed to the next iteration of the <code>for</code> loop. After entering the <code>while</code> loop, lines 22-23, a new ROC counts table is generated. The returned <code>list</code> is saved to <code>temp</code> at line 28, and if <code>temp[1] != -1</code> (i.e., <code>RocfitR</code> did converge) the AUC value is saved to <code>AUC[p]</code>, line 31. Upon exiting the code one has <code>P</code> values of AUC in the array <code>AUC</code>.</p>
<div id="parametric-auc-results" class="section level4 hasAnchor">
<h4><span class="header-section-number">1.8.2.1</span> Parametric AUC results<a href="sources-of-variability.html#parametric-auc-results" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The following code uses the function just described and prints out the results.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="sources-of-variability.html#cb15-1"></a>parametricFOM &lt;-<span class="st"> </span><span class="ot">TRUE</span></span>
<span id="cb15-2"><a href="sources-of-variability.html#cb15-2"></a>seed &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb15-3"><a href="sources-of-variability.html#cb15-3"></a><span class="kw">set.seed</span>(seed)</span>
<span id="cb15-4"><a href="sources-of-variability.html#cb15-4"></a>P &lt;-<span class="st"> </span><span class="dv">2000</span></span>
<span id="cb15-5"><a href="sources-of-variability.html#cb15-5"></a>RocCountsTable =<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb15-6"><a href="sources-of-variability.html#cb15-6"></a>RocCountsTable[<span class="dv">1</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">19</span>,<span class="dv">8</span>,<span class="dv">2</span>,<span class="dv">1</span>)</span>
<span id="cb15-7"><a href="sources-of-variability.html#cb15-7"></a>RocCountsTable[<span class="dv">2</span>,]  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">12</span>,<span class="dv">22</span>)</span>
<span id="cb15-8"><a href="sources-of-variability.html#cb15-8"></a>ret &lt;-<span class="st"> </span><span class="kw">doCalSimulator</span>(P, parametricFOM, RocCountsTable)</span>
<span id="cb15-9"><a href="sources-of-variability.html#cb15-9"></a>mu &lt;-<span class="st"> </span>ret<span class="op">$</span>mu</span>
<span id="cb15-10"><a href="sources-of-variability.html#cb15-10"></a>sigma &lt;-<span class="st"> </span>ret<span class="op">$</span>sigma</span>
<span id="cb15-11"><a href="sources-of-variability.html#cb15-11"></a>zetas &lt;-<span class="st"> </span>ret<span class="op">$</span>zetas</span>
<span id="cb15-12"><a href="sources-of-variability.html#cb15-12"></a>meanAUC_<span class="dv">1</span>_<span class="dv">2000</span> &lt;-<span class="st"> </span>ret<span class="op">$</span>meanAUC</span>
<span id="cb15-13"><a href="sources-of-variability.html#cb15-13"></a>stdAUC_<span class="dv">1</span>_<span class="dv">2000</span> &lt;-<span class="st"> </span>ret<span class="op">$</span>stdAUC</span></code></pre></div>
<p>After setting <code>parametricFOM</code> to <code>TRUE</code> (for a parametric fit), <code>seed</code> to 1 and <code>P</code> to 2000, the ROC counts table is defined and the function <code>doCalSimulator()</code> is called. The returned <code>list</code> contains the parameter values for the calibrated simulator: <span class="math inline">\(\mu\)</span> = 2.1735969, <span class="math inline">\(\sigma\)</span> = 1.6460988 and <span class="math inline">\(\zeta\)</span> = 0.0126342, 1.4753512, 2.4949012, 3.9452209. It also contains <code>OrigAUC</code>, the AUC of the original data, calculated by <code>RocfitR()</code>, in this case <code>OrigAUC</code> = 0.8704519, and the mean and standard deviation of the 2000 AUC values, equal to 0.8676727 and 0.0403331, respectively.</p>
<p>The simulations were repeated with <code>seed</code> = 2. This time the mean and standard deviation of the 2000 AUC values, are equal to 0.8681855 and 0.0405516, respectively. The respective values corresponding to the two <code>seed</code> values are quite close to each other (to within a percent).</p>
<p>More variability is observed, as expected, when the above two simulations are repeated with <code>P</code> = 200:</p>
<p>For <code>seed</code> = 1 and <code>P</code> = 200 the mean and standard deviation of the 200 AUC values, are 0.8727151 and 0.0355281, respectively.</p>
<p>For <code>seed</code> = 2 and <code>P</code> = 200 the mean and standard deviation of the 200 AUC values, are 0.8649385 and 0.0450947, respectively. Note the greater variability induced by the change in <code>seed</code>, as compared to <code>P</code> = 2000.</p>
</div>
<div id="non-parametric-auc-results" class="section level4 hasAnchor">
<h4><span class="header-section-number">1.8.2.2</span> Non-parametric AUC results<a href="sources-of-variability.html#non-parametric-auc-results" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The next simulation is with <code>seed</code> = 1 and <code>P</code> = 2000, but this time <code>parametricFOM</code> is set to <code>FALSE</code>. The calibration proceeds as before, using <code>RocfitR</code> to determine the parameters of the simulation model, calibrating the simulator requires a parametric fit, but this empirical AUC is used to obtained the 2000 AUC samples. The mean and standard deviation of the AUC values, are 0.8497634 and 0.0367476, respectively. Note that these are smaller than the corresponding parametric estimates. The empirical AUC is expected to be smaller than the corresponding parametric AUC as joining adjacent points with straight lines will underestimate the area under the smooth ROC curve. Repeating with <code>seed</code> = 2, the mean and standard deviation of the AUC values, are 0.8503732 and 0.0369091, respectively, which are close to the <code>seed</code> = 1 values.</p>
</div>
</div>
</div>
<div id="sources-of-variability-Discussion" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.9</span> Discussion<a href="sources-of-variability.html#sources-of-variability-Discussion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter focused on the factors affecting variability of AUC, namely case-sampling and between-reader variability, each of which contain an inseparable within-reader contribution. The only way to get an estimate of within-reader variability is to have the same reader re-interpret the same case-set on multiple occasions, after a sufficient time delay to minimize memory effects. This is rarely done and is unnecessary, in the ROC context, to sound experimental design and analysis. Some early publications have suggested that such re-interpretations are needed, but modern methods, described in the next part of the book, does not require re-interpretations. Indeed, it is a waste of precious reader-time resources. Rather than have the same readers re-interpret the same case-set on multiple occasions, it makes much more sense to recruit more readers and/or collect more cases, guided by a systematic sample size estimation method. Another reason I am not in favor of re-interpretations is that the within-reader variance is usually smaller than case-sampling and between-reader variances. Re-interpretations would minimize a quantity that is already small, which is not good practice.</p>
<p>The bootstrap and jackknife methods described in this chapter have wide applicability. Later they will be extended to estimating the covariance (essentially a scaled correlation) between two random variables. Also described was the DeLong method, applicable to the empirical AUC. Using a real dataset and simulators, all methods were shown to agree with each other, especially when the numbers of cases is large, Table 7.3 (row-D).</p>
<p>The concept of a calibrated simulator was introduced as a way of “anchoring” a simulator to a real dataset. While relatively easy for a single dataset, the concept has yet to be extended to where it would be useful, namely designing a simulator calibrated to a dataset consisting of interpretations by multiple readers in multiple modalities of a common dataset. Just as a calibrated simulator allowed comparison of the different variance estimation methods to a known standard, obtained by population sampling, a more general calibrated simulator would allow better testing the validity of the analysis described in the next few chapters.</p>
<p>This concludes Part A of this book. The next chapter begins Part B, namely the statistical analysis of multiple-reader multiple-case (MRMC) ROC datasets.</p>
<p>TBA: what to do with removed sections?</p>
</div>
<div id="sources-of-variability-references" class="section level2 hasAnchor">
<h2><span class="header-section-number">1.10</span> Chapter References<a href="sources-of-variability.html#sources-of-variability-references" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>



<h3>REFERENCES<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references">
<div id="ref-bamber1975area">
<p>Bamber, Donald. 1975. “The Area Above the Ordinal Dominance Graph and the Area Below the Receiver Operating Characteristic Graph.” <em>Journal of Mathematical Psychology</em> 12 (4): 387–415.</p>
</div>
<div id="ref-RN2261">
<p>Efron, Bradley, and Robert J. Tibshirani. 1993. <em>An Introduction to the Bootstrap</em>. Book. Vol. 57. Monographs on Statistics and Applied Probability. Boca Raton: Chapman; Hall/CRC.</p>
</div>
<div id="ref-RN2530">
<p>Noether, Gottfried E. 1967. “Elements of Nonparametric Statistics.” Report. Wiley; Sons.</p>
</div>
<div id="ref-RN412">
<p>Swets, John A., and Ronald M. Pickett. 1982. <em>Evaluation of Diagnostic Systems: Methods from Signal Detection Theory</em>. Book. First. Series in Cognition and Perception. New York: Academic Press.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hypothesis-testing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocSigTestBook.pdf", "RJafrocSigTestBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
